//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.HelpersLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.HelpersLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        internal static string ActionsCodeMenuEntry_FilePath_File_path {
            get {
                return ResourceManager.GetString("ActionsCodeMenuEntry_FilePath_File_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path without extension + &quot;Output file name extension&quot;.
        /// </summary>
        internal static string ActionsCodeMenuEntry_OutputFilePath_File_path_without_extension____Output_file_name_extension_ {
            get {
                return ResourceManager.GetString("ActionsCodeMenuEntry_OutputFilePath_File_path_without_extension____Output_file_na" +
                        "me_extension_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image effects / watermark.
        /// </summary>
        internal static string AfterCaptureTasks_AddImageEffects {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_AddImageEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in image editor.
        /// </summary>
        internal static string AfterCaptureTasks_AnnotateImage {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_AnnotateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file path to clipboard.
        /// </summary>
        internal static string AfterCaptureTasks_CopyFilePathToClipboard {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_CopyFilePathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file to clipboard.
        /// </summary>
        internal static string AfterCaptureTasks_CopyFileToClipboard {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_CopyFileToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy image to clipboard.
        /// </summary>
        internal static string AfterCaptureTasks_CopyImageToClipboard {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_CopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file locally.
        /// </summary>
        internal static string AfterCaptureTasks_DeleteFile {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform actions.
        /// </summary>
        internal static string AfterCaptureTasks_PerformActions {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_PerformActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image to file.
        /// </summary>
        internal static string AfterCaptureTasks_SaveImageToFile {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_SaveImageToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image to file as....
        /// </summary>
        internal static string AfterCaptureTasks_SaveImageToFileWithDialog {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_SaveImageToFileWithDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save thumbnail image to file.
        /// </summary>
        internal static string AfterCaptureTasks_SaveThumbnailImageToFile {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_SaveThumbnailImageToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print image.
        /// </summary>
        internal static string AfterCaptureTasks_SendImageToPrinter {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_SendImageToPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image to host.
        /// </summary>
        internal static string AfterCaptureTasks_UploadImageToHost {
            get {
                return ResourceManager.GetString("AfterCaptureTasks_UploadImageToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL to clipboard.
        /// </summary>
        internal static string AfterUploadTasks_CopyURLToClipboard {
            get {
                return ResourceManager.GetString("AfterUploadTasks_CopyURLToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL.
        /// </summary>
        internal static string AfterUploadTasks_OpenURL {
            get {
                return ResourceManager.GetString("AfterUploadTasks_OpenURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share URL.
        /// </summary>
        internal static string AfterUploadTasks_ShareURL {
            get {
                return ResourceManager.GetString("AfterUploadTasks_ShareURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show QR code window.
        /// </summary>
        internal static string AfterUploadTasks_ShowQRCode {
            get {
                return ResourceManager.GetString("AfterUploadTasks_ShowQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorten URL.
        /// </summary>
        internal static string AfterUploadTasks_UseURLShortener {
            get {
                return ResourceManager.GetString("AfterUploadTasks_UseURLShortener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard content: File (Count: {0}).
        /// </summary>
        internal static string ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_content__File__Count___0__ {
            get {
                return ResourceManager.GetString("ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_content__File__Count" +
                        "___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard content: Image (Size: {0}x{1}).
        /// </summary>
        internal static string ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_content__Image__Size___0_x_1__ {
            get {
                return ResourceManager.GetString("ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_content__Image__Size" +
                        "___0_x_1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard content: Text (Length: {0}).
        /// </summary>
        internal static string ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_content__Text__Length___0__ {
            get {
                return ResourceManager.GetString("ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_content__Text__Lengt" +
                        "h___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty or contains unknown data..
        /// </summary>
        internal static string ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_is_empty_or_contains_unknown_data_ {
            get {
                return ResourceManager.GetString("ClipboardContentViewer_ClipboardContentViewer_Load_Clipboard_is_empty_or_contains" +
                        "_unknown_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan: {0:0.0}%, Magenta: {1:0.0}%, Yellow: {2:0.0}%, Key: {3:0.0}%.
        /// </summary>
        internal static string CMYK_ToString_Cyan___0_0_0____Magenta___1_0_0____Yellow___2_0_0____Key___3_0_0__ {
            get {
                return ResourceManager.GetString("CMYK_ToString_Cyan___0_0_0____Magenta___1_0_0____Yellow___2_0_0____Key___3_0_0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CodeMenu_Create_Close {
            get {
                return ResourceManager.GetString("CodeMenu_Create_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Crosshair {
            get {
                object obj = ResourceManager.GetObject("Crosshair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a Cascading Style Sheet....
        /// </summary>
        internal static string CssFileNameEditor_EditValue_Browse_for_a_Cascading_Style_Sheet___ {
            get {
                return ResourceManager.GetString("CssFileNameEditor_EditValue_Browse_for_a_Cascading_Style_Sheet___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a folder....
        /// </summary>
        internal static string DirectoryNameEditor_EditValue_Browse_for_a_folder___ {
            get {
                return ResourceManager.GetString("DirectoryNameEditor_EditValue_Browse_for_a_folder___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS successfully set..
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_DNS_successfully_set_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_DNS_successfully_set_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS successfully set. Reboot is required..
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_DNS_successfully_set__Reboot_is_required_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_DNS_successfully_set__Reboot_is_required_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting DNS failed..
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_Setting_DNS_failed_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_Setting_DNS_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting DNS failed with error code:.
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_Setting_DNS_failed_with_error_code_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_Setting_DNS_failed_with_error_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string DNSChangerForm_DNSChangerForm_Manual {
            get {
                return ResourceManager.GetString("DNSChangerForm_DNSChangerForm_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0:0.0}%
        ///Download speed: {1:0.0} KB/s
        ///File size: {2:n0} / {3:n0} KB.
        /// </summary>
        internal static string DownloaderForm_ChangeProgress_Progress {
            get {
                return ResourceManager.GetString("DownloaderForm_ChangeProgress_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        internal static string DownloaderForm_ChangeStatus_Status___0_ {
            get {
                return ResourceManager.GetString("DownloaderForm_ChangeStatus_Status___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename: {0}.
        /// </summary>
        internal static string DownloaderForm_DownloaderForm_Filename___0_ {
            get {
                return ResourceManager.GetString("DownloaderForm_DownloaderForm_Filename___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting..
        /// </summary>
        internal static string DownloaderForm_DownloaderForm_Waiting_ {
            get {
                return ResourceManager.GetString("DownloaderForm_DownloaderForm_Waiting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed..
        /// </summary>
        internal static string DownloaderForm_fileDownloader_DownloadCompleted_Download_completed_ {
            get {
                return ResourceManager.GetString("DownloaderForm_fileDownloader_DownloadCompleted_Download_completed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string DownloaderForm_fileDownloader_DownloadCompleted_Install {
            get {
                return ResourceManager.GetString("DownloaderForm_fileDownloader_DownloadCompleted_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DownloaderForm_StartDownload_Cancel {
            get {
                return ResourceManager.GetString("DownloaderForm_StartDownload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading..
        /// </summary>
        internal static string DownloaderForm_StartDownload_Downloading_ {
            get {
                return ResourceManager.GetString("DownloaderForm_StartDownload_Downloading_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting file size..
        /// </summary>
        internal static string DownloaderForm_StartDownload_Getting_file_size_ {
            get {
                return ResourceManager.GetString("DownloaderForm_StartDownload_Getting_file_size_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for executable....
        /// </summary>
        internal static string ExeFileNameEditor_EditValue_Browse_for_executable___ {
            get {
                return ResourceManager.GetString("ExeFileNameEditor_EditValue_Browse_for_executable___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed..
        /// </summary>
        internal static string ExportImportControl_Deserialize_Import_failed_ {
            get {
                return ResourceManager.GetString("ExportImportControl_Deserialize_Import_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed..
        /// </summary>
        internal static string ExportImportControl_Serialize_Export_failed_ {
            get {
                return ResourceManager.GetString("ExportImportControl_Serialize_Export_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings copied to your clipboard..
        /// </summary>
        internal static string ExportImportControl_tsmiExportClipboard_Click_Settings_copied_to_your_clipboard_ {
            get {
                return ResourceManager.GetString("ExportImportControl_tsmiExportClipboard_Click_Settings_copied_to_your_clipboard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to download settings from.
        /// </summary>
        internal static string ExportImportControl_tsmiImportURL_Click_URL_to_download_settings_from {
            get {
                return ResourceManager.GetString("ExportImportControl_tsmiImportURL_Click_URL_to_download_settings_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Extensions_AddContextMenu_Copy {
            get {
                return ResourceManager.GetString("Extensions_AddContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Extensions_AddContextMenu_Cut {
            get {
                return ResourceManager.GetString("Extensions_AddContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Extensions_AddContextMenu_Paste {
            get {
                return ResourceManager.GetString("Extensions_AddContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom file uploader.
        /// </summary>
        internal static string FileDestination_CustomFileUploader {
            get {
                return ResourceManager.GetString("FileDestination_CustomFileUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string FileDestination_Email {
            get {
                return ResourceManager.GetString("FileDestination_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared folder.
        /// </summary>
        internal static string FileDestination_SharedFolder {
            get {
                return ResourceManager.GetString("FileDestination_SharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask what to do.
        /// </summary>
        internal static string FileExistAction_Ask {
            get {
                return ResourceManager.GetString("FileExistAction_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not save.
        /// </summary>
        internal static string FileExistAction_Cancel {
            get {
                return ResourceManager.GetString("FileExistAction_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite file.
        /// </summary>
        internal static string FileExistAction_Overwrite {
            get {
                return ResourceManager.GetString("FileExistAction_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append number to the filename.
        /// </summary>
        internal static string FileExistAction_UniqueName {
            get {
                return ResourceManager.GetString("FileExistAction_UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        internal static string FolderSelectDialog_Title_Select_a_folder {
            get {
                return ResourceManager.GetString("FolderSelectDialog_Title_Select_a_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octree quantizer 16 colors.
        /// </summary>
        internal static string GIFQuality_Bit4 {
            get {
                return ResourceManager.GetString("GIFQuality_Bit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octree quantizer 256 colors (Slow encoding but better quality).
        /// </summary>
        internal static string GIFQuality_Bit8 {
            get {
                return ResourceManager.GetString("GIFQuality_Bit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default .NET encoding (Fast encoding but average quality).
        /// </summary>
        internal static string GIFQuality_Default {
            get {
                return ResourceManager.GetString("GIFQuality_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette quantizer grayscale 256 colors.
        /// </summary>
        internal static string GIFQuality_Grayscale {
            get {
                return ResourceManager.GetString("GIFQuality_Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file path.
        /// </summary>
        internal static string HashCheckForm_btnFilePathBrowse_Click_Choose_file_path {
            get {
                return ResourceManager.GetString("HashCheckForm_btnFilePathBrowse_Click_Choose_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create directory, check your path settings..
        /// </summary>
        internal static string Helpers_CreateDirectoryIfNotExist_Create_failed_ {
            get {
                return ResourceManager.GetString("Helpers_CreateDirectoryIfNotExist_Create_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed:.
        /// </summary>
        internal static string Helpers_DownloadString_Download_failed_ {
            get {
                return ResourceManager.GetString("Helpers_DownloadString_Download_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not exist:.
        /// </summary>
        internal static string Helpers_OpenFolder_Folder_not_exist_ {
            get {
                return ResourceManager.GetString("Helpers_OpenFolder_Folder_not_exist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture active monitor.
        /// </summary>
        internal static string HotkeyType_ActiveMonitor {
            get {
                return ResourceManager.GetString("HotkeyType_ActiveMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_ActiveMonitor_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ActiveMonitor_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture active window.
        /// </summary>
        internal static string HotkeyType_ActiveWindow {
            get {
                return ResourceManager.GetString("HotkeyType_ActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_ActiveWindow_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ActiveWindow_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto capture.
        /// </summary>
        internal static string HotkeyType_AutoCapture {
            get {
                return ResourceManager.GetString("HotkeyType_AutoCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_AutoCapture_Category {
            get {
                return ResourceManager.GetString("HotkeyType_AutoCapture_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Stop Automate tool.
        /// </summary>
        internal static string HotkeyType_Automate {
            get {
                return ResourceManager.GetString("HotkeyType_Automate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_Automate_Category {
            get {
                return ResourceManager.GetString("HotkeyType_Automate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload from clipboard.
        /// </summary>
        internal static string HotkeyType_ClipboardUpload {
            get {
                return ResourceManager.GetString("HotkeyType_ClipboardUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string HotkeyType_ClipboardUpload_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ClipboardUpload_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload from clipboard with content viewer.
        /// </summary>
        internal static string HotkeyType_ClipboardUploadWithContentViewer {
            get {
                return ResourceManager.GetString("HotkeyType_ClipboardUploadWithContentViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string HotkeyType_ClipboardUploadWithContentViewer_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ClipboardUploadWithContentViewer_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color picker.
        /// </summary>
        internal static string HotkeyType_ColorPicker {
            get {
                return ResourceManager.GetString("HotkeyType_ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_ColorPicker_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ColorPicker_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture custom region.
        /// </summary>
        internal static string HotkeyType_CustomRegion {
            get {
                return ResourceManager.GetString("HotkeyType_CustomRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_CustomRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_CustomRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture diamond region.
        /// </summary>
        internal static string HotkeyType_DiamondRegion {
            get {
                return ResourceManager.GetString("HotkeyType_DiamondRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_DiamondRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_DiamondRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop upload.
        /// </summary>
        internal static string HotkeyType_DragDropUpload {
            get {
                return ResourceManager.GetString("HotkeyType_DragDropUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string HotkeyType_DragDropUpload_Category {
            get {
                return ResourceManager.GetString("HotkeyType_DragDropUpload_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture ellipse region.
        /// </summary>
        internal static string HotkeyType_EllipseRegion {
            get {
                return ResourceManager.GetString("HotkeyType_EllipseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_EllipseRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_EllipseRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string HotkeyType_FileUpload {
            get {
                return ResourceManager.GetString("HotkeyType_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string HotkeyType_FileUpload_Category {
            get {
                return ResourceManager.GetString("HotkeyType_FileUpload_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload folder.
        /// </summary>
        internal static string HotkeyType_FolderUpload {
            get {
                return ResourceManager.GetString("HotkeyType_FolderUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string HotkeyType_FolderUpload_Category {
            get {
                return ResourceManager.GetString("HotkeyType_FolderUpload_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture freehand region.
        /// </summary>
        internal static string HotkeyType_FreeHandRegion {
            get {
                return ResourceManager.GetString("HotkeyType_FreeHandRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_FreeHandRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_FreeHandRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP client.
        /// </summary>
        internal static string HotkeyType_FTPClient {
            get {
                return ResourceManager.GetString("HotkeyType_FTPClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_FTPClient_Category {
            get {
                return ResourceManager.GetString("HotkeyType_FTPClient_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash check.
        /// </summary>
        internal static string HotkeyType_HashCheck {
            get {
                return ResourceManager.GetString("HotkeyType_HashCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_HashCheck_Category {
            get {
                return ResourceManager.GetString("HotkeyType_HashCheck_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image effects.
        /// </summary>
        internal static string HotkeyType_ImageEffects {
            get {
                return ResourceManager.GetString("HotkeyType_ImageEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_ImageEffects_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ImageEffects_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index folder.
        /// </summary>
        internal static string HotkeyType_IndexFolder {
            get {
                return ResourceManager.GetString("HotkeyType_IndexFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_IndexFolder_Category {
            get {
                return ResourceManager.GetString("HotkeyType_IndexFolder_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture last region.
        /// </summary>
        internal static string HotkeyType_LastRegion {
            get {
                return ResourceManager.GetString("HotkeyType_LastRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_LastRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_LastRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string HotkeyType_None {
            get {
                return ResourceManager.GetString("HotkeyType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open screenshots folder.
        /// </summary>
        internal static string HotkeyType_OpenScreenshotsFolder {
            get {
                return ResourceManager.GetString("HotkeyType_OpenScreenshotsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string HotkeyType_OpenScreenshotsFolder_Category {
            get {
                return ResourceManager.GetString("HotkeyType_OpenScreenshotsFolder_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture polygon region.
        /// </summary>
        internal static string HotkeyType_PolygonRegion {
            get {
                return ResourceManager.GetString("HotkeyType_PolygonRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_PolygonRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_PolygonRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture entire screen.
        /// </summary>
        internal static string HotkeyType_PrintScreen {
            get {
                return ResourceManager.GetString("HotkeyType_PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_PrintScreen_Category {
            get {
                return ResourceManager.GetString("HotkeyType_PrintScreen_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code.
        /// </summary>
        internal static string HotkeyType_QRCode {
            get {
                return ResourceManager.GetString("HotkeyType_QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_QRCode_Category {
            get {
                return ResourceManager.GetString("HotkeyType_QRCode_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture rectangle region (Annotate).
        /// </summary>
        internal static string HotkeyType_RectangleAnnotate {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleAnnotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_RectangleAnnotate_Category {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleAnnotate_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture rectangle region (Light).
        /// </summary>
        internal static string HotkeyType_RectangleLight {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_RectangleLight_Category {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleLight_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture rectangle region.
        /// </summary>
        internal static string HotkeyType_RectangleRegion {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_RectangleRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture rectangle region (Transparent).
        /// </summary>
        internal static string HotkeyType_RectangleTransparent {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_RectangleTransparent_Category {
            get {
                return ResourceManager.GetString("HotkeyType_RectangleTransparent_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture rounded rectangle region.
        /// </summary>
        internal static string HotkeyType_RoundedRectangleRegion {
            get {
                return ResourceManager.GetString("HotkeyType_RoundedRectangleRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_RoundedRectangleRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_RoundedRectangleRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruler.
        /// </summary>
        internal static string HotkeyType_Ruler {
            get {
                return ResourceManager.GetString("HotkeyType_Ruler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_Ruler_Category {
            get {
                return ResourceManager.GetString("HotkeyType_Ruler_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen color picker.
        /// </summary>
        internal static string HotkeyType_ScreenColorPicker {
            get {
                return ResourceManager.GetString("HotkeyType_ScreenColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_ScreenColorPicker_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ScreenColorPicker_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen recording.
        /// </summary>
        internal static string HotkeyType_ScreenRecorder {
            get {
                return ResourceManager.GetString("HotkeyType_ScreenRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen record.
        /// </summary>
        internal static string HotkeyType_ScreenRecorder_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ScreenRecorder_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen recording (GIF).
        /// </summary>
        internal static string HotkeyType_ScreenRecorderGIF {
            get {
                return ResourceManager.GetString("HotkeyType_ScreenRecorderGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen record.
        /// </summary>
        internal static string HotkeyType_ScreenRecorderGIF_Category {
            get {
                return ResourceManager.GetString("HotkeyType_ScreenRecorderGIF_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start auto capture using last region.
        /// </summary>
        internal static string HotkeyType_StartAutoCapture {
            get {
                return ResourceManager.GetString("HotkeyType_StartAutoCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_StartAutoCapture_Category {
            get {
                return ResourceManager.GetString("HotkeyType_StartAutoCapture_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start screen recording using last region.
        /// </summary>
        internal static string HotkeyType_StartScreenRecorder {
            get {
                return ResourceManager.GetString("HotkeyType_StartScreenRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen record.
        /// </summary>
        internal static string HotkeyType_StartScreenRecorder_Category {
            get {
                return ResourceManager.GetString("HotkeyType_StartScreenRecorder_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start screen recording (GIF) using last region.
        /// </summary>
        internal static string HotkeyType_StartScreenRecorderGIF {
            get {
                return ResourceManager.GetString("HotkeyType_StartScreenRecorderGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen record.
        /// </summary>
        internal static string HotkeyType_StartScreenRecorderGIF_Category {
            get {
                return ResourceManager.GetString("HotkeyType_StartScreenRecorderGIF_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all active uploads.
        /// </summary>
        internal static string HotkeyType_StopUploads {
            get {
                return ResourceManager.GetString("HotkeyType_StopUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string HotkeyType_StopUploads_Category {
            get {
                return ResourceManager.GetString("HotkeyType_StopUploads_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture triangle region.
        /// </summary>
        internal static string HotkeyType_TriangleRegion {
            get {
                return ResourceManager.GetString("HotkeyType_TriangleRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_TriangleRegion_Category {
            get {
                return ResourceManager.GetString("HotkeyType_TriangleRegion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet message.
        /// </summary>
        internal static string HotkeyType_TweetMessage {
            get {
                return ResourceManager.GetString("HotkeyType_TweetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string HotkeyType_TweetMessage_Category {
            get {
                return ResourceManager.GetString("HotkeyType_TweetMessage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload from URL.
        /// </summary>
        internal static string HotkeyType_UploadURL {
            get {
                return ResourceManager.GetString("HotkeyType_UploadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string HotkeyType_UploadURL_Category {
            get {
                return ResourceManager.GetString("HotkeyType_UploadURL_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture rectangle region (Window).
        /// </summary>
        internal static string HotkeyType_WindowRectangle {
            get {
                return ResourceManager.GetString("HotkeyType_WindowRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen capture.
        /// </summary>
        internal static string HotkeyType_WindowRectangle_Category {
            get {
                return ResourceManager.GetString("HotkeyType_WindowRectangle_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue: {0:0.0}°, Saturation: {1:0.0}%, Brightness: {2:0.0}%.
        /// </summary>
        internal static string HSB_ToString_ {
            get {
                return ResourceManager.GetString("HSB_ToString_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom image uploader.
        /// </summary>
        internal static string ImageDestination_CustomImageUploader {
            get {
                return ResourceManager.GetString("ImageDestination_CustomImageUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploader.
        /// </summary>
        internal static string ImageDestination_FileUploader {
            get {
                return ResourceManager.GetString("ImageDestination_FileUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MyMessageBox_MyMessageBox_Cancel {
            get {
                return ResourceManager.GetString("MyMessageBox_MyMessageBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string MyMessageBox_MyMessageBox_No {
            get {
                return ResourceManager.GetString("MyMessageBox_MyMessageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MyMessageBox_MyMessageBox_OK {
            get {
                return ResourceManager.GetString("MyMessageBox_MyMessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string MyMessageBox_MyMessageBox_Yes {
            get {
                return ResourceManager.GetString("MyMessageBox_MyMessageBox_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image....
        /// </summary>
        internal static string MyPictureBox_LoadImageAsync_Loading_image___ {
            get {
                return ResourceManager.GetString("MyPictureBox_LoadImageAsync_Loading_image___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image: {0}%.
        /// </summary>
        internal static string MyPictureBox_pbMain_LoadProgressChanged_Loading_image___0__ {
            get {
                return ResourceManager.GetString("MyPictureBox_pbMain_LoadProgressChanged_Loading_image___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tray balloon tip.
        /// </summary>
        internal static string PopUpNotificationType_BalloonTip {
            get {
                return ResourceManager.GetString("PopUpNotificationType_BalloonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show nothing.
        /// </summary>
        internal static string PopUpNotificationType_None {
            get {
                return ResourceManager.GetString("PopUpNotificationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toast notification with preview.
        /// </summary>
        internal static string PopUpNotificationType_ToastNotification {
            get {
                return ResourceManager.GetString("PopUpNotificationType_ToastNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintForm_LoadSettings_Print {
            get {
                return ResourceManager.GetString("PrintForm_LoadSettings_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}, Size: {1}.
        /// </summary>
        internal static string PrintTextForm_LoadSettings_Name___0___Size___1_ {
            get {
                return ResourceManager.GetString("PrintTextForm_LoadSettings_Name___0___Size___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string ProxyMethod_Automatic {
            get {
                return ResourceManager.GetString("ProxyMethod_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string ProxyMethod_Manual {
            get {
                return ResourceManager.GetString("ProxyMethod_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ProxyMethod_None {
            get {
                return ResourceManager.GetString("ProxyMethod_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload with {0}.
        /// </summary>
        internal static string RegistryHelpers_ShellExtDesc_Upload_with__0_ {
            get {
                return ResourceManager.GetString("RegistryHelpers_ShellExtDesc_Upload_with__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer name.
        /// </summary>
        internal static string ReplCodeMenuEntry_cn_Computer_name {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_cn_Computer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current day.
        /// </summary>
        internal static string ReplCodeMenuEntry_d_Current_day {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_d_Current_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current hour.
        /// </summary>
        internal static string ReplCodeMenuEntry_h_Current_hour {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_h_Current_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image height.
        /// </summary>
        internal static string ReplCodeMenuEntry_height_Gets_image_height {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_height_Gets_image_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto increment number.
        /// </summary>
        internal static string ReplCodeMenuEntry_i_Auto_increment_number {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_i_Auto_increment_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current minute.
        /// </summary>
        internal static string ReplCodeMenuEntry_mi_Current_minute {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_mi_Current_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current month.
        /// </summary>
        internal static string ReplCodeMenuEntry_mo_Current_month {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_mo_Current_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current month name (Local language).
        /// </summary>
        internal static string ReplCodeMenuEntry_mon_Current_month_name__Local_language_ {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_mon_Current_month_name__Local_language_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current month name (English).
        /// </summary>
        internal static string ReplCodeMenuEntry_mon2_Current_month_name__English_ {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_mon2_Current_month_name__English_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current millisecond.
        /// </summary>
        internal static string ReplCodeMenuEntry_ms_Current_millisecond {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_ms_Current_millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line.
        /// </summary>
        internal static string ReplCodeMenuEntry_n_New_line {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_n_New_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets AM/PM.
        /// </summary>
        internal static string ReplCodeMenuEntry_pm_Gets_AM_PM {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_pm_Gets_AM_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name of active window.
        /// </summary>
        internal static string ReplCodeMenuEntry_pn_Process_name_of_active_window {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_pn_Process_name_of_active_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random alphanumeric char.
        /// </summary>
        internal static string ReplCodeMenuEntry_ra_Random_alphanumeric_char {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_ra_Random_alphanumeric_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random number 0 to 9.
        /// </summary>
        internal static string ReplCodeMenuEntry_rn_Random_number_0_to_9 {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_rn_Random_number_0_to_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current second.
        /// </summary>
        internal static string ReplCodeMenuEntry_s_Current_second {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_s_Current_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of active window.
        /// </summary>
        internal static string ReplCodeMenuEntry_t_Title_of_active_window {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_t_Title_of_active_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login name.
        /// </summary>
        internal static string ReplCodeMenuEntry_uln_User_login_name {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_uln_User_login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string ReplCodeMenuEntry_un_User_name {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_un_User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix timestamp.
        /// </summary>
        internal static string ReplCodeMenuEntry_unix_Unix_timestamp {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_unix_Unix_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current week name (Local language).
        /// </summary>
        internal static string ReplCodeMenuEntry_w_Current_week_name__Local_language_ {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_w_Current_week_name__Local_language_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current week name (English).
        /// </summary>
        internal static string ReplCodeMenuEntry_w2_Current_week_name__English_ {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_w2_Current_week_name__English_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image width.
        /// </summary>
        internal static string ReplCodeMenuEntry_width_Gets_image_width {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_width_Gets_image_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current year.
        /// </summary>
        internal static string ReplCodeMenuEntry_y_Current_year {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_y_Current_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current year (2 digits).
        /// </summary>
        internal static string ReplCodeMenuEntry_yy_Current_year__2_digits_ {
            get {
                return ResourceManager.GetString("ReplCodeMenuEntry_yy_Current_year__2_digits_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response headers.
        /// </summary>
        internal static string ResponseType_Headers {
            get {
                return ResourceManager.GetString("ResponseType_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection URL.
        /// </summary>
        internal static string ResponseType_RedirectionURL {
            get {
                return ResourceManager.GetString("ResponseType_RedirectionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response text.
        /// </summary>
        internal static string ResponseType_Text {
            get {
                return ResourceManager.GetString("ResponseType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg (Good quality).
        /// </summary>
        internal static string ScreenRecordGIFEncoding_FFmpeg {
            get {
                return ResourceManager.GetString("ScreenRecordGIFEncoding_FFmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET (Bad quality).
        /// </summary>
        internal static string ScreenRecordGIFEncoding_NET {
            get {
                return ResourceManager.GetString("ScreenRecordGIFEncoding_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octree quantizer (Medium quality).
        /// </summary>
        internal static string ScreenRecordGIFEncoding_OctreeQuantizer {
            get {
                return ResourceManager.GetString("ScreenRecordGIFEncoding_OctreeQuantizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ShareX_Icon {
            get {
                object obj = ResourceManager.GetObject("ShareX_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShareX_Logo {
            get {
                object obj = ResourceManager.GetObject("ShareX_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShareX_Logo_Black {
            get {
                object obj = ResourceManager.GetObject("ShareX_Logo_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string SupportedLanguage_Automatic {
            get {
                return ResourceManager.GetString("SupportedLanguage_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom text uploader.
        /// </summary>
        internal static string TextDestination_CustomTextUploader {
            get {
                return ResourceManager.GetString("TextDestination_CustomTextUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploader.
        /// </summary>
        internal static string TextDestination_FileUploader {
            get {
                return ResourceManager.GetString("TextDestination_FileUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of {0} is available.
        /// </summary>
        internal static string UpdateCheckerLabel_UpdateControls_A_newer_version_of_ShareX_is_available {
            get {
                return ResourceManager.GetString("UpdateCheckerLabel_UpdateControls_A_newer_version_of_ShareX_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is up to date.
        /// </summary>
        internal static string UpdateCheckerLabel_UpdateControls_ShareX_is_up_to_date {
            get {
                return ResourceManager.GetString("UpdateCheckerLabel_UpdateControls_ShareX_is_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed.
        /// </summary>
        internal static string UpdateCheckerLabel_UpdateControls_Update_check_failed {
            get {
                return ResourceManager.GetString("UpdateCheckerLabel_UpdateControls_Update_check_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of {0} is available.
        ///Would you like to download and install it?.
        /// </summary>
        internal static string UpdateMessageBox_UpdateMessageBox_ {
            get {
                return ResourceManager.GetString("UpdateMessageBox_UpdateMessageBox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is available.
        /// </summary>
        internal static string UpdateMessageBox_UpdateMessageBox_update_is_available {
            get {
                return ResourceManager.GetString("UpdateMessageBox_UpdateMessageBox_update_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string URLSharingServices_Email {
            get {
                return ResourceManager.GetString("URLSharingServices_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom URL shortener.
        /// </summary>
        internal static string UrlShortenerType_CustomURLShortener {
            get {
                return ResourceManager.GetString("UrlShortenerType_CustomURLShortener", resourceCulture);
            }
        }
    }
}
