//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.ScreenCaptureLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.ScreenCaptureLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Crosshair {
            get {
                object obj = ResourceManager.GetObject("Crosshair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg error.
        /// </summary>
        internal static string FFmpegHelper_Record_FFmpeg_error {
            get {
                return ResourceManager.GetString("FFmpegHelper_Record_FFmpeg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for ffmpeg.exe.
        /// </summary>
        internal static string FFmpegOptionsForm_buttonFFmpegBrowse_Click_Browse_for_ffmpeg_exe {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_buttonFFmpegBrowse_Click_Browse_for_ffmpeg_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download of FFmpeg failed..
        /// </summary>
        internal static string FFmpegOptionsForm_DownloaderForm_InstallRequested_Download_of_FFmpeg_failed_ {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_DownloaderForm_InstallRequested_Download_of_FFmpeg_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded FFmpeg..
        /// </summary>
        internal static string FFmpegOptionsForm_DownloaderForm_InstallRequested_Successfully_downloaded_FFmpeg_ {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_DownloaderForm_InstallRequested_Successfully_downloaded_FFmpeg_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate: {0}k.
        /// </summary>
        internal static string FFmpegOptionsForm_UpdateUI_Bitrate___0_k {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_UpdateUI_Bitrate___0_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        internal static string FFmpegOptionsForm_UpdateUI_Quality_ {
            get {
                return ResourceManager.GetString("FFmpegOptionsForm_UpdateUI_Quality_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl: Drawing mode ░ Space: Fullscreen capture.
        /// </summary>
        internal static string RectangleAnnotate_DrawTips_Drawing_mode_off {
            get {
                return ResourceManager.GetString("RectangleAnnotate_DrawTips_Drawing_mode_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl: Region mode ░ Shift: Pen color ░ Mouse wheel: Pen size ░ Space: Fullscreen capture.
        /// </summary>
        internal static string RectangleAnnotate_DrawTips_Drawing_mode_on {
            get {
                return ResourceManager.GetString("RectangleAnnotate_DrawTips_Drawing_mode_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle capture annotate.
        /// </summary>
        internal static string RectangleAnnotate_InitializeComponent_Rectangle_capture_annotate {
            get {
                return ResourceManager.GetString("RectangleAnnotate_InitializeComponent_Rectangle_capture_annotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle capture light.
        /// </summary>
        internal static string RectangleLight_InitializeComponent_Rectangle_capture_light {
            get {
                return ResourceManager.GetString("RectangleLight_InitializeComponent_Rectangle_capture_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0} / Y: {1}
        ///W: {2} / H: {3}.
        /// </summary>
        internal static string RectangleRegion_GetAreaText_Area {
            get {
                return ResourceManager.GetString("RectangleRegion_GetAreaText_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0}, Y: {1}
        ///R: {2}, G: {3}, B: {4}.
        /// </summary>
        internal static string RectangleRegion_GetColorPickerText {
            get {
                return ResourceManager.GetString("RectangleRegion_GetColorPickerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0} / Y: {1} / X2: {2} / Y2: {3}
        ///Width: {4} px / Height: {5} px
        ///Distance: {6:0.00} px / Angle: {7:0.00}°.
        /// </summary>
        internal static string RectangleRegion_GetRulerText_Ruler_info {
            get {
                return ResourceManager.GetString("RectangleRegion_GetRulerText_Ruler_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region capture.
        /// </summary>
        internal static string Surface_InitializeComponent_Region_capture {
            get {
                return ResourceManager.GetString("Surface_InitializeComponent_Region_capture", resourceCulture);
            }
        }
    }
}
