//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.ImageEditor.Localization {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Strings() {
        }

        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("ShareX.ImageEditor.Localization.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }

        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string ConfirmationDialogView_Title {
            get {
                return ResourceManager.GetString("ConfirmationDialogView_Title", resourceCulture);
            }
        }
        public static string ConfirmationDialogView_Message {
            get {
                return ResourceManager.GetString("ConfirmationDialogView_Message", resourceCulture);
            }
        }
        public static string ConfirmationDialogView_Yes {
            get {
                return ResourceManager.GetString("ConfirmationDialogView_Yes", resourceCulture);
            }
        }
        public static string ConfirmationDialogView_No {
            get {
                return ResourceManager.GetString("ConfirmationDialogView_No", resourceCulture);
            }
        }
        public static string ConfirmationDialogView_Cancel {
            get {
                return ResourceManager.GetString("ConfirmationDialogView_Cancel", resourceCulture);
            }
        }
        public static string NewImageDialogView_Title {
            get {
                return ResourceManager.GetString("NewImageDialogView_Title", resourceCulture);
            }
        }
        public static string NewImageDialogView_Width {
            get {
                return ResourceManager.GetString("NewImageDialogView_Width", resourceCulture);
            }
        }
        public static string NewImageDialogView_Pixels {
            get {
                return ResourceManager.GetString("NewImageDialogView_Pixels", resourceCulture);
            }
        }
        public static string NewImageDialogView_Height {
            get {
                return ResourceManager.GetString("NewImageDialogView_Height", resourceCulture);
            }
        }
        public static string NewImageDialogView_Background {
            get {
                return ResourceManager.GetString("NewImageDialogView_Background", resourceCulture);
            }
        }
        public static string NewImageDialogView_Transparent {
            get {
                return ResourceManager.GetString("NewImageDialogView_Transparent", resourceCulture);
            }
        }
        public static string NewImageDialogView_SolidColor {
            get {
                return ResourceManager.GetString("NewImageDialogView_SolidColor", resourceCulture);
            }
        }
        public static string NewImageDialogView_OK {
            get {
                return ResourceManager.GetString("NewImageDialogView_OK", resourceCulture);
            }
        }
        public static string NewImageDialogView_Cancel {
            get {
                return ResourceManager.GetString("NewImageDialogView_Cancel", resourceCulture);
            }
        }
        public static string StartScreenDialogView_Title {
            get {
                return ResourceManager.GetString("StartScreenDialogView_Title", resourceCulture);
            }
        }
        public static string StartScreenDialogView_CreateNewImage {
            get {
                return ResourceManager.GetString("StartScreenDialogView_CreateNewImage", resourceCulture);
            }
        }
        public static string StartScreenDialogView_OpenImageFile {
            get {
                return ResourceManager.GetString("StartScreenDialogView_OpenImageFile", resourceCulture);
            }
        }
        public static string StartScreenDialogView_LoadImageFromClipboard {
            get {
                return ResourceManager.GetString("StartScreenDialogView_LoadImageFromClipboard", resourceCulture);
            }
        }
        public static string StartScreenDialogView_LoadImageFromURL {
            get {
                return ResourceManager.GetString("StartScreenDialogView_LoadImageFromURL", resourceCulture);
            }
        }
        public static string StartScreenDialogView_Load {
            get {
                return ResourceManager.GetString("StartScreenDialogView_Load", resourceCulture);
            }
        }
        public static string StartScreenDialogView_Cancel {
            get {
                return ResourceManager.GetString("StartScreenDialogView_Cancel", resourceCulture);
            }
        }
        public static string StartScreenDialogView_Exit {
            get {
                return ResourceManager.GetString("StartScreenDialogView_Exit", resourceCulture);
            }
        }
        public static string StartScreenDialogView_RecentFiles {
            get {
                return ResourceManager.GetString("StartScreenDialogView_RecentFiles", resourceCulture);
            }
        }
        public static string StartScreenDialogView_NoRecentImageFiles {
            get {
                return ResourceManager.GetString("StartScreenDialogView_NoRecentImageFiles", resourceCulture);
            }
        }
        public static string StartScreenDialogView_InvalidURL {
            get {
                return ResourceManager.GetString("StartScreenDialogView_InvalidURL", resourceCulture);
            }
        }
    }
}
