//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changelog.
        /// </summary>
        public static string AboutForm_AboutForm_Changelog {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contributors.
        /// </summary>
        public static string AboutForm_AboutForm_Contributors {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External libraries.
        /// </summary>
        public static string AboutForm_AboutForm_External_libraries {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm_External_libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Issues.
        /// </summary>
        public static string AboutForm_AboutForm_Issues {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project page.
        /// </summary>
        public static string AboutForm_AboutForm_Project_page {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm_Project_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translators.
        /// </summary>
        public static string AboutForm_AboutForm_Translators {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm_Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Website.
        /// </summary>
        public static string AboutForm_AboutForm_Website {
            get {
                return ResourceManager.GetString("AboutForm_AboutForm_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File path can&apos;t be empty..
        /// </summary>
        public static string ActionsForm_btnOK_Click_File_path_can_t_be_empty_ {
            get {
                return ResourceManager.GetString("ActionsForm_btnOK_Click_File_path_can_t_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name can&apos;t be empty..
        /// </summary>
        public static string ActionsForm_btnOK_Click_Name_can_t_be_empty_ {
            get {
                return ResourceManager.GetString("ActionsForm_btnOK_Click_Name_can_t_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose file path.
        /// </summary>
        public static string ActionsForm_btnPathBrowse_Click_Choose_file_path {
            get {
                return ResourceManager.GetString("ActionsForm_btnPathBrowse_Click_Choose_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_block {
            get {
                object obj = ResourceManager.GetObject("application_block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_blog {
            get {
                object obj = ResourceManager.GetObject("application_blog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_blue {
            get {
                object obj = ResourceManager.GetObject("application_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_browser {
            get {
                object obj = ResourceManager.GetObject("application_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_icon_large {
            get {
                object obj = ResourceManager.GetObject("application_icon_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_monitor {
            get {
                object obj = ResourceManager.GetObject("application_monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_network {
            get {
                object obj = ResourceManager.GetObject("application_network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_task {
            get {
                object obj = ResourceManager.GetObject("application_task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose screenshots folder path.
        /// </summary>
        public static string ApplicationSettingsForm_btnBrowseCustomScreenshotsPath_Click_Choose_screenshots_folder_path {
            get {
                return ResourceManager.GetString("ApplicationSettingsForm_btnBrowseCustomScreenshotsPath_Click_Choose_screenshots_f" +
                        "older_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose ShareX personal folder path.
        /// </summary>
        public static string ApplicationSettingsForm_btnBrowsePersonalFolderPath_Click_Choose_ShareX_personal_folder_path {
            get {
                return ResourceManager.GetString("ApplicationSettingsForm_btnBrowsePersonalFolderPath_Click_Choose_ShareX_personal_" +
                        "folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ShareX need to be restarted for language changes to apply.
        ///Would you like to restart ShareX?.
        /// </summary>
        public static string ApplicationSettingsForm_cbLanguage_SelectedIndexChanged_Language_Restart {
            get {
                return ResourceManager.GetString("ApplicationSettingsForm_cbLanguage_SelectedIndexChanged_Language_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For settings to take effect ShareX needs to be reopened from Steam..
        /// </summary>
        public static string ApplicationSettingsForm_cbSteamShowInApp_CheckedChanged_For_settings_to_take_effect_ShareX_needs_to_be_reopened_from_Steam_ {
            get {
                return ResourceManager.GetString("ApplicationSettingsForm_cbSteamShowInApp_CheckedChanged_For_settings_to_take_effe" +
                        "ct_ShareX_needs_to_be_reopened_from_Steam_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_090 {
            get {
                object obj = ResourceManager.GetObject("arrow_090", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_270 {
            get {
                object obj = ResourceManager.GetObject("arrow_270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap au {
            get {
                object obj = ResourceManager.GetObject("au", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string AutoCaptureForm_Execute_Start {
            get {
                return ResourceManager.GetString("AutoCaptureForm_Execute_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string AutoCaptureForm_Execute_Stop {
            get {
                return ResourceManager.GetString("AutoCaptureForm_Execute_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X: {0}, Y: {1}, Width: {2}, Height: {3}.
        /// </summary>
        public static string AutoCaptureForm_UpdateRegion_X___0___Y___1___Width___2___Height___3_ {
            get {
                return ResourceManager.GetString("AutoCaptureForm_UpdateRegion_X___0___Y___1___Width___2___Height___3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeleft: {0}s ({1}%) Total: {2}.
        /// </summary>
        public static string AutoCaptureForm_UpdateStatus_Timeleft___0_s___1____Total___2_ {
            get {
                return ResourceManager.GetString("AutoCaptureForm_UpdateStatus_Timeleft___0_s___1____Total___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap balloon_white {
            get {
                object obj = ResourceManager.GetObject("balloon_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap barcode_2d {
            get {
                object obj = ResourceManager.GetObject("barcode_2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom.
        /// </summary>
        public static string BeforeUploadControl_AddDestination_Custom {
            get {
                return ResourceManager.GetString("BeforeUploadControl_AddDestination_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is about to be uploaded to {1}. You may choose a different destination..
        /// </summary>
        public static string BeforeUploadForm_BeforeUploadForm__0__is_about_to_be_uploaded_to__1___You_may_choose_a_different_destination_ {
            get {
                return ResourceManager.GetString("BeforeUploadForm_BeforeUploadForm__0__is_about_to_be_uploaded_to__1___You_may_cho" +
                        "ose_a_different_destination_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose a destination..
        /// </summary>
        public static string BeforeUploadForm_BeforeUploadForm_Please_choose_a_destination_ {
            get {
                return ResourceManager.GetString("BeforeUploadForm_BeforeUploadForm_Please_choose_a_destination_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bin {
            get {
                object obj = ResourceManager.GetObject("bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap br {
            get {
                object obj = ResourceManager.GetObject("br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap camcorder_image {
            get {
                object obj = ResourceManager.GetObject("camcorder_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap camcorder_pencil {
            get {
                object obj = ResourceManager.GetObject("camcorder_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream CaptureSound {
            get {
                return ResourceManager.GetStream("CaptureSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap categories {
            get {
                object obj = ResourceManager.GetObject("categories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap checkbox_check {
            get {
                object obj = ResourceManager.GetObject("checkbox_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap checkbox_uncheck {
            get {
                object obj = ResourceManager.GetObject("checkbox_uncheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chrome support enabled..
        /// </summary>
        public static string ChromeForm_btnRegister_Click_Chrome_support_enabled_ {
            get {
                return ResourceManager.GetString("ChromeForm_btnRegister_Click_Chrome_support_enabled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chrome support disabled..
        /// </summary>
        public static string ChromeForm_btnUnregister_Click_Chrome_support_disabled_ {
            get {
                return ResourceManager.GetString("ChromeForm_btnUnregister_Click_Chrome_support_disabled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clipboard {
            get {
                object obj = ResourceManager.GetObject("clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clipboard_list {
            get {
                object obj = ResourceManager.GetObject("clipboard_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supported variables: {0} and other variables such as {1} etc..
        /// </summary>
        public static string ClipboardFormatForm_ClipboardFormatForm_Supported_variables___0__and_other_variables_such_as__1__etc_ {
            get {
                return ResourceManager.GetString("ClipboardFormatForm_ClipboardFormatForm_Supported_variables___0__and_other_variab" +
                        "les_such_as__1__etc_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cn {
            get {
                object obj = ResourceManager.GetObject("cn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap color {
            get {
                object obj = ResourceManager.GetObject("color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CompanionCube {
            get {
                object obj = ResourceManager.GetObject("CompanionCube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap control_record {
            get {
                object obj = ResourceManager.GetObject("control_record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap control_record_yellow {
            get {
                object obj = ResourceManager.GetObject("control_record_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cross_button {
            get {
                object obj = ResourceManager.GetObject("cross_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap crown {
            get {
                object obj = ResourceManager.GetObject("crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Diamond {
            get {
                object obj = ResourceManager.GetObject("Diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_break {
            get {
                object obj = ResourceManager.GetObject("document-break", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_copy {
            get {
                object obj = ResourceManager.GetObject("document_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_globe {
            get {
                object obj = ResourceManager.GetObject("document_globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap drive {
            get {
                object obj = ResourceManager.GetObject("drive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap drive_globe {
            get {
                object obj = ResourceManager.GetObject("drive_globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drop
        ///here.
        /// </summary>
        public static string DropForm_DrawDropImage_Drop_here {
            get {
                return ResourceManager.GetString("DropForm_DrawDropImage_Drop_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap edit_scale {
            get {
                object obj = ResourceManager.GetObject("edit_scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ellipse {
            get {
                object obj = ResourceManager.GetObject("Ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension can&apos;t be empty..
        /// </summary>
        public static string EncoderProgramForm_btnOK_Click_Extension_can_t_be_empty_ {
            get {
                return ResourceManager.GetString("EncoderProgramForm_btnOK_Click_Extension_can_t_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path can&apos;t be empty..
        /// </summary>
        public static string EncoderProgramForm_btnOK_Click_Path_can_t_be_empty_ {
            get {
                return ResourceManager.GetString("EncoderProgramForm_btnOK_Click_Path_can_t_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose encoder path.
        /// </summary>
        public static string EncoderProgramForm_btnPathBrowse_Click_Choose_encoder_path {
            get {
                return ResourceManager.GetString("EncoderProgramForm_btnPathBrowse_Click_Choose_encoder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap eraser {
            get {
                object obj = ResourceManager.GetObject("eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ErrorSound {
            get {
                return ResourceManager.GetStream("ErrorSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap es {
            get {
                object obj = ResourceManager.GetObject("es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exclamation_button {
            get {
                object obj = ResourceManager.GetObject("exclamation_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use new name: .
        /// </summary>
        public static string FileExistForm_txtNewName_TextChanged_Use_new_name__ {
            get {
                return ResourceManager.GetString("FileExistForm_txtNewName_TextChanged_Use_new_name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap film {
            get {
                object obj = ResourceManager.GetObject("film", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_open_document {
            get {
                object obj = ResourceManager.GetObject("folder_open_document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_open_image {
            get {
                object obj = ResourceManager.GetObject("folder_open_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_tree {
            get {
                object obj = ResourceManager.GetObject("folder_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr {
            get {
                object obj = ResourceManager.GetObject("fr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FreeHand {
            get {
                object obj = ResourceManager.GetObject("FreeHand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fullscreen {
            get {
                object obj = ResourceManager.GetObject("Fullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GitHub {
            get {
                object obj = ResourceManager.GetObject("GitHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap globe {
            get {
                object obj = ResourceManager.GetObject("globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap globe_pencil {
            get {
                object obj = ResourceManager.GetObject("globe_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap globe_share {
            get {
                object obj = ResourceManager.GetObject("globe_share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap google_plus {
            get {
                object obj = ResourceManager.GetObject("google_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hotkey.
        /// </summary>
        public static string HotkeyManager_ShowFailedHotkeys_hotkey {
            get {
                return ResourceManager.GetString("HotkeyManager_ShowFailedHotkeys_hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkey registration failed.
        /// </summary>
        public static string HotkeyManager_ShowFailedHotkeys_Hotkey_registration_failed {
            get {
                return ResourceManager.GetString("HotkeyManager_ShowFailedHotkeys_Hotkey_registration_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hotkeys.
        /// </summary>
        public static string HotkeyManager_ShowFailedHotkeys_hotkeys {
            get {
                return ResourceManager.GetString("HotkeyManager_ShowFailedHotkeys_hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to register {0}:
        ///
        ///{1}
        ///
        ///Please select a different hotkey or quit the conflicting application and reopen ShareX..
        /// </summary>
        public static string HotkeyManager_ShowFailedHotkeys_Unable_to_register_hotkey {
            get {
                return ResourceManager.GetString("HotkeyManager_ShowFailedHotkeys_Unable_to_register_hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a hotkey....
        /// </summary>
        public static string HotkeySelectionControl_StartEditing_Select_a_hotkey___ {
            get {
                return ResourceManager.GetString("HotkeySelectionControl_StartEditing_Select_a_hotkey___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hu {
            get {
                object obj = ResourceManager.GetObject("hu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_export {
            get {
                object obj = ResourceManager.GetObject("image_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_pencil {
            get {
                object obj = ResourceManager.GetObject("image_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_saturation {
            get {
                object obj = ResourceManager.GetObject("image_saturation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap images_stack {
            get {
                object obj = ResourceManager.GetObject("images_stack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap inbox {
            get {
                object obj = ResourceManager.GetObject("inbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap keyboard__minus {
            get {
                object obj = ResourceManager.GetObject("keyboard__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap keyboard__plus {
            get {
                object obj = ResourceManager.GetObject("keyboard__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kr {
            get {
                object obj = ResourceManager.GetObject("kr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer {
            get {
                object obj = ResourceManager.GetObject("layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer_pencil {
            get {
                object obj = ResourceManager.GetObject("layer_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer_shape {
            get {
                object obj = ResourceManager.GetObject("layer_shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer_shape_curve {
            get {
                object obj = ResourceManager.GetObject("layer_shape_curve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer_shape_ellipse {
            get {
                object obj = ResourceManager.GetObject("layer_shape_ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer_shape_polygon {
            get {
                object obj = ResourceManager.GetObject("layer_shape_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer_shape_round {
            get {
                object obj = ResourceManager.GetObject("layer_shape_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layer_transparent {
            get {
                object obj = ResourceManager.GetObject("layer_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layers_arrange {
            get {
                object obj = ResourceManager.GetObject("layers_arrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layers_ungroup {
            get {
                object obj = ResourceManager.GetObject("layers_ungroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layout_select_content {
            get {
                object obj = ResourceManager.GetObject("layout_select_content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap layout_select_sidebar {
            get {
                object obj = ResourceManager.GetObject("layout_select_sidebar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can single left click the ShareX tray icon to start region capture..
        /// </summary>
        public static string MainForm_AfterShownJobs_You_can_single_left_click_the_ShareX_tray_icon_to_start_region_capture_ {
            get {
                return ResourceManager.GetString("MainForm_AfterShownJobs_You_can_single_left_click_the_ShareX_tray_icon_to_start_r" +
                        "egion_capture_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete this file?.
        /// </summary>
        public static string MainForm_tsmiDeleteSelectedFile_Click_Do_you_really_want_to_delete_this_file_ {
            get {
                return ResourceManager.GetString("MainForm_tsmiDeleteSelectedFile_Click_Do_you_really_want_to_delete_this_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File delete confirmation.
        /// </summary>
        public static string MainForm_tsmiDeleteSelectedFile_Click_File_delete_confirmation {
            get {
                return ResourceManager.GetString("MainForm_tsmiDeleteSelectedFile_Click_File_delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text upload test.
        /// </summary>
        public static string MainForm_tsmiTestTextUpload_Click_Text_upload_test {
            get {
                return ResourceManager.GetString("MainForm_tsmiTestTextUpload_Click_Text_upload_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currently configured hotkeys:.
        /// </summary>
        public static string MainForm_UpdateMainFormTip_Currently_configured_hotkeys_ {
            get {
                return ResourceManager.GetString("MainForm_UpdateMainFormTip_Currently_configured_hotkeys_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can drag and drop files to this window..
        /// </summary>
        public static string MainForm_UpdateMainFormTip_You_can_drag_and_drop_files_to_this_window_ {
            get {
                return ResourceManager.GetString("MainForm_UpdateMainFormTip_You_can_drag_and_drop_files_to_this_window_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide menu.
        /// </summary>
        public static string MainForm_UpdateMenu_Hide_menu {
            get {
                return ResourceManager.GetString("MainForm_UpdateMenu_Hide_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show menu.
        /// </summary>
        public static string MainForm_UpdateMenu_Show_menu {
            get {
                return ResourceManager.GetString("MainForm_UpdateMenu_Show_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable hotkeys.
        /// </summary>
        public static string MainForm_UpdateToggleHotkeyButton_Disable_hotkeys {
            get {
                return ResourceManager.GetString("MainForm_UpdateToggleHotkeyButton_Disable_hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable hotkeys.
        /// </summary>
        public static string MainForm_UpdateToggleHotkeyButton_Enable_hotkeys {
            get {
                return ResourceManager.GetString("MainForm_UpdateToggleHotkeyButton_Enable_hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add workflows from hotkey settings....
        /// </summary>
        public static string MainForm_UpdateWorkflowsMenu_You_can_add_workflows_from_hotkey_settings___ {
            get {
                return ResourceManager.GetString("MainForm_UpdateWorkflowsMenu_You_can_add_workflows_from_hotkey_settings___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap navigation_000_button {
            get {
                object obj = ResourceManager.GetObject("navigation_000_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap navigation_090_button {
            get {
                object obj = ResourceManager.GetObject("navigation_090_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap network_ip {
            get {
                object obj = ResourceManager.GetObject("network_ip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nl {
            get {
                object obj = ResourceManager.GetObject("nl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notebook {
            get {
                object obj = ResourceManager.GetObject("notebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pipette {
            get {
                object obj = ResourceManager.GetObject("pipette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Polygon {
            get {
                object obj = ResourceManager.GetObject("Polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Program_Run_Error {
            get {
                return ResourceManager.GetString("Program_Run_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create folder:.
        /// </summary>
        public static string Program_Run_Unable_to_create_folder_ {
            get {
                return ResourceManager.GetString("Program_Run_Unable_to_create_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t access to &quot;{0}&quot; file.
        ///Please run ShareX as administrator to change personal folder path..
        /// </summary>
        public static string Program_WritePersonalPathConfig_Cant_access_to_file {
            get {
                return ResourceManager.GetString("Program_WritePersonalPathConfig_Cant_access_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left click to copy URL to clipboard. Right click to open URL..
        /// </summary>
        public static string RecentManager_UpdateRecentMenu_Left_click_to_copy_URL_to_clipboard__Right_click_to_open_URL_ {
            get {
                return ResourceManager.GetString("RecentManager_UpdateRecentMenu_Left_click_to_copy_URL_to_clipboard__Right_click_t" +
                        "o_open_URL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rectangle {
            get {
                object obj = ResourceManager.GetObject("Rectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap robot {
            get {
                object obj = ResourceManager.GetObject("robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RoundedRectangle {
            get {
                object obj = ResourceManager.GetObject("RoundedRectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ru {
            get {
                object obj = ResourceManager.GetObject("ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ruler_triangle {
            get {
                object obj = ResourceManager.GetObject("ruler_triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cursor position (X, Y) = {0}, {1}.
        /// </summary>
        public static string ScreenColorPicker_btnCopyAll_Click_Cursor_position {
            get {
                return ResourceManager.GetString("ScreenColorPicker_btnCopyAll_Click_Cursor_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string ScreenColorPicker_ScreenColorPicker_Close {
            get {
                return ResourceManager.GetString("ScreenColorPicker_ScreenColorPicker_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start screen color picker.
        /// </summary>
        public static string ScreenColorPicker_UpdateControls_Start_screen_color_picker {
            get {
                return ResourceManager.GetString("ScreenColorPicker_UpdateControls_Start_screen_color_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop screen color picker.
        /// </summary>
        public static string ScreenColorPicker_UpdateControls_Stop_screen_color_picker {
            get {
                return ResourceManager.GetString("ScreenColorPicker_UpdateControls_Stop_screen_color_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download of FFmpeg failed..
        /// </summary>
        public static string ScreenRecordForm_DownloaderForm_InstallRequested_Download_of_FFmpeg_failed_ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_DownloaderForm_InstallRequested_Download_of_FFmpeg_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFmpeg successfully downloaded..
        /// </summary>
        public static string ScreenRecordForm_DownloaderForm_InstallRequested_FFmpeg_successfully_downloaded_ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_DownloaderForm_InstallRequested_FFmpeg_successfully_downloaded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CLI video encoder file does not exist: .
        /// </summary>
        public static string ScreenRecordForm_StartRecording_CLI_video_encoder_file_does_not_exist__ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_CLI_video_encoder_file_does_not_exist__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to start recording..
        /// </summary>
        public static string ScreenRecordForm_StartRecording_Click_tray_icon_to_start_recording_ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Click_tray_icon_to_start_recording_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to stop recording..
        /// </summary>
        public static string ScreenRecordForm_StartRecording_Click_tray_icon_to_stop_recording_ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Click_tray_icon_to_stop_recording_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} does not exist.
        ///
        ///Would you like to automatically download it?.
        /// </summary>
        public static string ScreenRecordForm_StartRecording_does_not_exist {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Encoding....
        /// </summary>
        public static string ScreenRecordForm_StartRecording_Encoding___ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Encoding___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFmpeg error.
        /// </summary>
        public static string ScreenRecordForm_StartRecording_FFmpeg_error {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_FFmpeg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFmpeg video and audio source both can&apos;t be &quot;None&quot;..
        /// </summary>
        public static string ScreenRecordForm_StartRecording_FFmpeg_video_and_audio_source_both_can_t_be__None__ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_FFmpeg_video_and_audio_source_both_can_t_be__None" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing.
        /// </summary>
        public static string ScreenRecordForm_StartRecording_Missing {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no valid CLI video encoder selected..
        /// </summary>
        public static string ScreenRecordForm_StartRecording_There_is_no_valid_CLI_video_encoder_selected_ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_There_is_no_valid_CLI_video_encoder_selected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting....
        /// </summary>
        public static string ScreenRecordForm_StartRecording_Waiting___ {
            get {
                return ResourceManager.GetString("ScreenRecordForm_StartRecording_Waiting___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap steam {
            get {
                object obj = ResourceManager.GetObject("steam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream TaskCompletedSound {
            get {
                return ResourceManager.GetStream("TaskCompletedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FTP client only supports FTP or FTPS..
        /// </summary>
        public static string TaskHelpers_OpenFTPClient_FTP_client_only_supports_FTP_or_FTPS_ {
            get {
                return ResourceManager.GetString("TaskHelpers_OpenFTPClient_FTP_client_only_supports_FTP_or_FTPS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to find valid FTP account..
        /// </summary>
        public static string TaskHelpers_OpenFTPClient_Unable_to_find_valid_FTP_account_ {
            get {
                return ResourceManager.GetString("TaskHelpers_OpenFTPClient_Unable_to_find_valid_FTP_account_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image editor - How to load image?.
        /// </summary>
        public static string TaskHelpers_OpenImageEditor_Image_editor___How_to_load_image_ {
            get {
                return ResourceManager.GetString("TaskHelpers_OpenImageEditor_Image_editor___How_to_load_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your clipboard contains image, would you like to open it in image editor?
        ///
        ///Press yes to open image from clipboard. Alternatively, press no to open image file dialog box..
        /// </summary>
        public static string TaskHelpers_OpenImageEditor_Your_clipboard_contains_image {
            get {
                return ResourceManager.GetString("TaskHelpers_OpenImageEditor_Your_clipboard_contains_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copied to clipboard: {0}.
        /// </summary>
        public static string TaskHelpers_OpenQuickScreenColorPicker_Copied_to_clipboard___0_ {
            get {
                return ResourceManager.GetString("TaskHelpers_OpenQuickScreenColorPicker_Copied_to_clipboard___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkeys disabled..
        /// </summary>
        public static string TaskHelpers_ToggleHotkeys_Hotkeys_disabled_ {
            get {
                return ResourceManager.GetString("TaskHelpers_ToggleHotkeys_Hotkeys_disabled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkeys enabled..
        /// </summary>
        public static string TaskHelpers_ToggleHotkeys_Hotkeys_enabled_ {
            get {
                return ResourceManager.GetString("TaskHelpers_ToggleHotkeys_Hotkeys_enabled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tweet successfully sent..
        /// </summary>
        public static string TaskHelpers_TweetMessage_Tweet_successfully_sent_ {
            get {
                return ResourceManager.GetString("TaskHelpers_TweetMessage_Tweet_successfully_sent_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to find valid Twitter account..
        /// </summary>
        public static string TaskHelpers_TweetMessage_Unable_to_find_valid_Twitter_account_ {
            get {
                return ResourceManager.GetString("TaskHelpers_TweetMessage_Unable_to_find_valid_Twitter_account_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In queue.
        /// </summary>
        public static string TaskManager_CreateListViewItem_In_queue {
            get {
                return ResourceManager.GetString("TaskManager_CreateListViewItem_In_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string TaskManager_task_UploadCompleted_Error {
            get {
                return ResourceManager.GetString("TaskManager_task_UploadCompleted_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task completed.
        /// </summary>
        public static string TaskManager_task_UploadCompleted_ShareX___Task_completed {
            get {
                return ResourceManager.GetString("TaskManager_task_UploadCompleted_ShareX___Task_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configure CLI video encoders ---&gt;.
        /// </summary>
        public static string TaskSettingsForm_ConfigureEncoder_Configure_CLI_video_encoders_____ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_ConfigureEncoder_Configure_CLI_video_encoders_____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview:.
        /// </summary>
        public static string TaskSettingsForm_txtNameFormatPatternActiveWindow_TextChanged_Preview_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_txtNameFormatPatternActiveWindow_TextChanged_Preview_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After capture: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_After_capture___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_After_capture___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After upload: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_After_upload___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_After_upload___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File uploader: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_File_uploader___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_File_uploader___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image uploader: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_Image_uploader___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_Image_uploader___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_Task___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_Task___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text uploader: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_Text_uploader___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_Text_uploader___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL sharing service: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_URL_sharing_service___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_URL_sharing_service___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL shortener: {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateUploaderMenuNames_URL_shortener___0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateUploaderMenuNames_URL_shortener___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task settings.
        /// </summary>
        public static string TaskSettingsForm_UpdateWindowTitle_Task_settings {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateWindowTitle_Task_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task settings for {0}.
        /// </summary>
        public static string TaskSettingsForm_UpdateWindowTitle_Task_settings_for__0_ {
            get {
                return ResourceManager.GetString("TaskSettingsForm_UpdateWindowTitle_Task_settings_for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tick_button {
            get {
                object obj = ResourceManager.GetObject("tick_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolbox {
            get {
                object obj = ResourceManager.GetObject("toolbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tr {
            get {
                object obj = ResourceManager.GetObject("tr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap traffic_cone {
            get {
                object obj = ResourceManager.GetObject("traffic_cone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Triangle {
            get {
                object obj = ResourceManager.GetObject("Triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Twitter {
            get {
                object obj = ResourceManager.GetObject("Twitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_scroll_pane_image {
            get {
                object obj = ResourceManager.GetObject("ui_scroll_pane_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap upload_cloud {
            get {
                object obj = ResourceManager.GetObject("upload_cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload errors.
        /// </summary>
        public static string UploadInfoManager_ShowErrors_Upload_errors {
            get {
                return ResourceManager.GetString("UploadInfoManager_ShowErrors_Upload_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download failed:
        ///{0}.
        /// </summary>
        public static string UploadManager_DownloadAndUploadFile_Download_failed {
            get {
                return ResourceManager.GetString("UploadManager_DownloadAndUploadFile_Download_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to upload {0} files?.
        /// </summary>
        public static string UploadManager_IsUploadConfirmed_Are_you_sure_you_want_to_upload__0__files_ {
            get {
                return ResourceManager.GetString("UploadManager_IsUploadConfirmed_Are_you_sure_you_want_to_upload__0__files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t show this message again..
        /// </summary>
        public static string UploadManager_IsUploadConfirmed_Don_t_show_this_message_again_ {
            get {
                return ResourceManager.GetString("UploadManager_IsUploadConfirmed_Don_t_show_this_message_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload files.
        /// </summary>
        public static string UploadManager_IsUploadConfirmed_Upload_files {
            get {
                return ResourceManager.GetString("UploadManager_IsUploadConfirmed_Upload_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File upload.
        /// </summary>
        public static string UploadManager_UploadFile_File_upload {
            get {
                return ResourceManager.GetString("UploadManager_UploadFile_File_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder upload.
        /// </summary>
        public static string UploadManager_UploadFolder_Folder_upload {
            get {
                return ResourceManager.GetString("UploadManager_UploadFolder_Folder_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL to download from and upload.
        /// </summary>
        public static string UploadManager_UploadURL_URL_to_download_from_and_upload {
            get {
                return ResourceManager.GetString("UploadManager_UploadURL_URL_to_download_from_and_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share URL ({0}).
        /// </summary>
        public static string UploadTask_CreateShareURLTask_Share_URL___0__ {
            get {
                return ResourceManager.GetString("UploadTask_CreateShareURLTask_Share_URL___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shorten URL ({0}).
        /// </summary>
        public static string UploadTask_CreateURLShortenerTask_Shorten_URL___0__ {
            get {
                return ResourceManager.GetString("UploadTask_CreateURLShortenerTask_Shorten_URL___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a folder to save.
        /// </summary>
        public static string UploadTask_DoAfterCaptureJobs_Choose_a_folder_to_save {
            get {
                return ResourceManager.GetString("UploadTask_DoAfterCaptureJobs_Choose_a_folder_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First time upload warning.
        /// </summary>
        public static string UploadTask_DoUploadJob_First_time_upload_warning {
            get {
                return ResourceManager.GetString("UploadTask_DoUploadJob_First_time_upload_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to upload this screenshot?
        ///Press &apos;No&apos; to cancel the current upload and disable screenshot auto uploading..
        /// </summary>
        public static string UploadTask_DoUploadJob_First_time_upload_warning_text {
            get {
                return ResourceManager.GetString("UploadTask_DoUploadJob_First_time_upload_warning_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading.
        /// </summary>
        public static string UploadTask_DoUploadJob_Uploading {
            get {
                return ResourceManager.GetString("UploadTask_DoUploadJob_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are attempting to upload a large file.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string UploadTask_DoUploadJob_You_are_attempting_to_upload_a_large_file {
            get {
                return ResourceManager.GetString("UploadTask_DoUploadJob_You_are_attempting_to_upload_a_large_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading.
        /// </summary>
        public static string UploadTask_DownloadAndUpload_Downloading {
            get {
                return ResourceManager.GetString("UploadTask_DownloadAndUpload_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        public static string UploadTask_OnUploadCompleted_Done {
            get {
                return ResourceManager.GetString("UploadTask_OnUploadCompleted_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopped.
        /// </summary>
        public static string UploadTask_OnUploadCompleted_Stopped {
            get {
                return ResourceManager.GetString("UploadTask_OnUploadCompleted_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing.
        /// </summary>
        public static string UploadTask_Prepare_Preparing {
            get {
                return ResourceManager.GetString("UploadTask_Prepare_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting.
        /// </summary>
        public static string UploadTask_Prepare_Starting {
            get {
                return ResourceManager.GetString("UploadTask_Prepare_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopping.
        /// </summary>
        public static string UploadTask_Stop_Stopping {
            get {
                return ResourceManager.GetString("UploadTask_Stop_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL is empty..
        /// </summary>
        public static string UploadTask_ThreadDoWork_URL_is_empty_ {
            get {
                return ResourceManager.GetString("UploadTask_ThreadDoWork_URL_is_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap us {
            get {
                object obj = ResourceManager.GetObject("us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose folder path.
        /// </summary>
        public static string WatchFolderForm_btnPathBrowse_Click_Choose_folder_path {
            get {
                return ResourceManager.GetString("WatchFolderForm_btnPathBrowse_Click_Choose_folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capture.
        /// </summary>
        public static string WebpageCaptureForm_UpdateControls_Capture {
            get {
                return ResourceManager.GetString("WebpageCaptureForm_UpdateControls_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string WebpageCaptureForm_UpdateControls_Stop {
            get {
                return ResourceManager.GetString("WebpageCaptureForm_UpdateControls_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wrench_screwdriver {
            get {
                object obj = ResourceManager.GetObject("wrench_screwdriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
