//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.ImageEffectsLib.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.ImageEffectsLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Adjustments과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Adjustments {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Drawings {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Drawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Filters {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manipulations과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Manipulations {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Manipulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageEffectsForm_EditorMode_Cancel {
            get {
                return ResourceManager.GetString("ImageEffectsForm_EditorMode_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image effects - Width: {0}, Height: {1}, Render time: {2} ms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageEffectsForm_UpdatePreview_Image_effects___Width___0___Height___1___Render_time___2__ms {
            get {
                return ResourceManager.GetString("ImageEffectsForm_UpdatePreview_Image_effects___Width___0___Height___1___Render_ti" +
                        "me___2__ms", resourceCulture);
            }
        }
    }
}
