//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.ImageEffectsLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.ImageEffectsLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Adjustments {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawings.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Drawings {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Drawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Filters {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulations.
        /// </summary>
        internal static string ImageEffectsForm_AddAllEffectsToTreeView_Manipulations {
            get {
                return ResourceManager.GetString("ImageEffectsForm_AddAllEffectsToTreeView_Manipulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image effects - Width: {0}, Height: {1}, Render time: {2} ms.
        /// </summary>
        internal static string ImageEffectsForm_UpdatePreview_Image_effects___Width___0___Height___1___Render_time___2__ms {
            get {
                return ResourceManager.GetString("ImageEffectsForm_UpdatePreview_Image_effects___Width___0___Height___1___Render_ti" +
                        "me___2__ms", resourceCulture);
            }
        }
    }
}
