//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.ScreenCaptureLib.Localization {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Strings() { }

        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("ShareX.ScreenCaptureLib.Localization.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }

        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        public static string FFmpegOptionsWindow_Title {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Title", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Screen_recording {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Screen_recording", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Description {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Description", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Reset_encoding_options {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Reset_encoding_options", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Reset_options {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Reset_options", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Reset_all_options {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Reset_all_options", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Cancel {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Cancel", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Reset {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Reset", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Sources {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Sources", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Video {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Video", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Audio {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Audio", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Advanced {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Advanced", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_FFmpeg_executable {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_FFmpeg_executable", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Use_custom_path {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Use_custom_path", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Path_to_ffmpeg {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Path_to_ffmpeg", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Browse_for_ffmpeg {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Browse_for_ffmpeg", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Capture_sources {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Capture_sources", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Refresh_devices {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Refresh_devices", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Video_source {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Video_source", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Choose_video_source {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Choose_video_source", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Audio_source {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Audio_source", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Choose_audio_source {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Choose_audio_source", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Looking_for_devices {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Looking_for_devices", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Get_recorder_devices {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Get_recorder_devices", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Video_encoder {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Video_encoder", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Encoder_settings {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Encoder_settings", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Faster_presets_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Faster_presets_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Slow_presets_warning {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Slow_presets_warning", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Use_target_bitrate {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Use_target_bitrate", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Constant_rate_factor {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Constant_rate_factor", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_CRF_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_CRF_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Target_bitrate {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Target_bitrate", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Variable_bitrate_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Variable_bitrate_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Variable_bitrate_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Variable_bitrate_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Tune {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Tune", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Palette_mode {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Palette_mode", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Dithering_mode {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Dithering_mode", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Bayer_scale {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Bayer_scale", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Bayer_scale_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Bayer_scale_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Usage {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Usage", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_No_additional_settings {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_No_additional_settings", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Audio_encoder {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Audio_encoder", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Animated_formats_no_audio {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Animated_formats_no_audio", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Bitrate {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Bitrate", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Lower_values_higher_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Lower_values_higher_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Additional_arguments {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Additional_arguments", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Arguments_example {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Arguments_example", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_FFmpeg_command {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_FFmpeg_command", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Use_custom_commands {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Use_custom_commands", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Custom_command_placeholders {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Custom_command_placeholders", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_FFmpeg_not_found {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_FFmpeg_not_found", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Device_enumeration_failed {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Device_enumeration_failed", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_One_device_found {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_One_device_found", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Multiple_devices_found {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Multiple_devices_found", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_No_devices_found {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_No_devices_found", resourceCulture); }
        }
        public static string ScreenRecordWindow_Title {
            get { return ResourceManager.GetString("ScreenRecordWindow_Title", resourceCulture); }
        }
        public static string ScreenRecordWindow_Start {
            get { return ResourceManager.GetString("ScreenRecordWindow_Start", resourceCulture); }
        }
        public static string ScreenRecordWindow_Pause {
            get { return ResourceManager.GetString("ScreenRecordWindow_Pause", resourceCulture); }
        }
        public static string ScreenRecordWindow_Restart {
            get { return ResourceManager.GetString("ScreenRecordWindow_Restart", resourceCulture); }
        }
        public static string ScreenRecordWindow_Abort {
            get { return ResourceManager.GetString("ScreenRecordWindow_Abort", resourceCulture); }
        }
        public static string ScreenRecordWindow_Abort_this_recording {
            get { return ResourceManager.GetString("ScreenRecordWindow_Abort_this_recording", resourceCulture); }
        }
        public static string ScreenRecordWindow_Cancel {
            get { return ResourceManager.GetString("ScreenRecordWindow_Cancel", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Title {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Title", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Capture {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Capture", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Upload_Save {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Upload_Save", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Copy {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Copy", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Options {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Options", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Help {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Help", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Select_scrollable_window {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Select_scrollable_window", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Ready {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Ready", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Options_heading {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Options_heading", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Start_delay {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Start_delay", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Milliseconds {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Milliseconds", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Scroll_delay {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Scroll_delay", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Scroll_method {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Scroll_method", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Scroll_amount {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Scroll_amount", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Times {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Times", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Automatically_scroll_to_top {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Automatically_scroll_to_top", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Auto_ignore_bottom_edge {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Auto_ignore_bottom_edge", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Show_capture_region {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Show_capture_region", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Automatically_upload_save {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Automatically_upload_save", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Cancel {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Cancel", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_OK {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_OK", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Stopping_capture {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Stopping_capture", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Selection_cancelled {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Selection_cancelled", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Capturing {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Capturing", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Capture_failed {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Capture_failed", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Capture_partially_successful {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Capture_partially_successful", resourceCulture); }
        }
        public static string ScrollingCaptureWindow_Capture_successful {
            get { return ResourceManager.GetString("ScrollingCaptureWindow_Capture_successful", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_CancelTaskEsc {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_CancelTaskEsc", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_UploadImage {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_UploadImage", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Highlight_color___ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Highlight_color___", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_SwitchToDrawingToolAfterSelection {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_SwitchToDrawingToolAfterSelection", resourceCulture); }
        }
        public static string CutOutEffectSize {
            get { return ResourceManager.GetString("CutOutEffectSize", resourceCulture); }
        }
        public static string ImageEffects {
            get { return ResourceManager.GetString("ImageEffects", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_FlipHorizontal {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_FlipHorizontal", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Multi_region_mode {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Multi_region_mode", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Pixel_size_ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Pixel_size_", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_ImageSize {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_ImageSize", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Delete {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Delete", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_ApplyChangesContinueTaskEnter {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_ApplyChangesContinueTaskEnter", resourceCulture); }
        }
        public static string OpenKeybindsPage {
            get { return ResourceManager.GetString("OpenKeybindsPage", resourceCulture); }
        }
        public static string Duplicate {
            get { return ResourceManager.GetString("Duplicate", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Edit {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Edit", resourceCulture); }
        }
        public static string ImageSaved {
            get { return ResourceManager.GetString("ImageSaved", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_AutoCloseEditorOnTask {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_AutoCloseEditorOnTask", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Undo {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Undo", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Redo {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Redo", resourceCulture); }
        }
        public static string RegionCaptureForm_InitializeComponent_ImageEditor {
            get { return ResourceManager.GetString("RegionCaptureForm_InitializeComponent_ImageEditor", resourceCulture); }
        }
        public static string BaseRegionForm_InitializeComponent_Region_capture {
            get { return ResourceManager.GetString("BaseRegionForm_InitializeComponent_Region_capture", resourceCulture); }
        }
        public static string RegionCaptureWindow_RectangleRegionTab {
            get { return ResourceManager.GetString("RegionCaptureWindow_RectangleRegionTab", resourceCulture); }
        }
        public static string EditorStartupForm_ClipboardDoesNotContainAnImage {
            get { return ResourceManager.GetString("EditorStartupForm_ClipboardDoesNotContainAnImage", resourceCulture); }
        }
        public static string NewLineCtrlEnterOKEnter {
            get { return ResourceManager.GetString("NewLineCtrlEnterOKEnter", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Capture_monitor {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_monitor", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_SendToBack {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_SendToBack", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Capture_active_monitor {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_active_monitor", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_BringForward {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_BringForward", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Rotate90CounterClockwise {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate90CounterClockwise", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_InterpolationMode {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_InterpolationMode", resourceCulture); }
        }
        public static string ScreenRecordForm_StartRecording_Click_tray_icon_to_stop_recording_ {
            get { return ResourceManager.GetString("ScreenRecordForm_StartRecording_Click_tray_icon_to_stop_recording_", resourceCulture); }
        }
        public static string ShapeManager_CenterPoints {
            get { return ResourceManager.GetString("ShapeManager_CenterPoints", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Options {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Options", resourceCulture); }
        }
        public static string ShapeManager_BorderStyle {
            get { return ResourceManager.GetString("ShapeManager_BorderStyle", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Capture {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture", resourceCulture); }
        }
        public static string RectangleRegion_GetAreaText_Area {
            get { return ResourceManager.GetString("RectangleRegion_GetAreaText_Area", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_OpenImageFile {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_OpenImageFile", resourceCulture); }
        }
        public static string Processing {
            get { return ResourceManager.GetString("Processing", resourceCulture); }
        }
        public static string ScreenRecordForm_StartRecording_Waiting___ {
            get { return ResourceManager.GetString("ScreenRecordForm_StartRecording_Waiting___", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Rotate90Clockwise {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate90Clockwise", resourceCulture); }
        }
        public static string CloseEsc {
            get { return ResourceManager.GetString("CloseEsc", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_StartingStepValue {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_StartingStepValue", resourceCulture); }
        }
        public static string Highlight {
            get { return ResourceManager.GetString("Highlight", resourceCulture); }
        }
        public static string MagnifyStrength {
            get { return ResourceManager.GetString("MagnifyStrength", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Corner_radius_ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Corner_radius_", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_PrintImage {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_PrintImage", resourceCulture); }
        }
        public static string NewLineEnterOKCtrlEnter {
            get { return ResourceManager.GetString("NewLineEnterOKCtrlEnter", resourceCulture); }
        }
        public static string ShapeManager_CursorType {
            get { return ResourceManager.GetString("ShapeManager_CursorType", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_DropShadow {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_DropShadow", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Square_shape_magnifier {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Square_shape_magnifier", resourceCulture); }
        }
        public static string Resume {
            get { return ResourceManager.GetString("Resume", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_EditorStartMode {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_EditorStartMode", resourceCulture); }
        }
        public static string ImageSavedAs {
            get { return ResourceManager.GetString("ImageSavedAs", resourceCulture); }
        }
        public static string ShapeManager_ArrowHeadDirection {
            get { return ResourceManager.GetString("ShapeManager_ArrowHeadDirection", resourceCulture); }
        }
        public static string ShapeManager_FreehandSmoothing {
            get { return ResourceManager.GetString("ShapeManager_FreehandSmoothing", resourceCulture); }
        }
        public static string ShapeManager_FreehandCurveInterpolation {
            get { return ResourceManager.GetString("ShapeManager_FreehandCurveInterpolation", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Capture_fullscreen {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Capture_fullscreen", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_CaptureRegions {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_CaptureRegions", resourceCulture); }
        }
        public static string RectangleLight_InitializeComponent_Rectangle_capture_light {
            get { return ResourceManager.GetString("RectangleLight_InitializeComponent_Rectangle_capture_light", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_SaveImage {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_SaveImage", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_NewImage {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_NewImage", resourceCulture); }
        }
        public static string Blur {
            get { return ResourceManager.GetString("Blur", resourceCulture); }
        }
        public static string ScreenRecordForm_StartRecording_Encoding___ {
            get { return ResourceManager.GetString("ScreenRecordForm_StartRecording_Encoding___", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Blur_radius_ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Blur_radius_", resourceCulture); }
        }
        public static string ImageUploading {
            get { return ResourceManager.GetString("ImageUploading", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_EnableAnimations {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_EnableAnimations", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_SendBackward {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_SendBackward", resourceCulture); }
        }
        public static string ImageCopied {
            get { return ResourceManager.GetString("ImageCopied", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Fill_color___ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Fill_color___", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_SaveImageAs {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_SaveImageAs", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_ContinueTaskSpaceOrRightClick {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_ContinueTaskSpaceOrRightClick", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_FontSize {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_FontSize", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_CanvasSize {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_CanvasSize", resourceCulture); }
        }
        public static string MenuIconSize {
            get { return ResourceManager.GetString("MenuIconSize", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_FlipVertical {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_FlipVertical", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_AutoCropImage {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_AutoCropImage", resourceCulture); }
        }
        public static string Pixelate {
            get { return ResourceManager.GetString("Pixelate", resourceCulture); }
        }
        public static string LockMenu {
            get { return ResourceManager.GetString("LockMenu", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_BringToFront {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_BringToFront", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Rotate180 {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Rotate180", resourceCulture); }
        }
        public static string LightResizeNodes {
            get { return ResourceManager.GetString("LightResizeNodes", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_LastRegion {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_LastRegion", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_InsertImageFromScreen {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_InsertImageFromScreen", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_DeleteAll {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_DeleteAll", resourceCulture); }
        }
        public static string AutoCopyImageToClipboard {
            get { return ResourceManager.GetString("AutoCopyImageToClipboard", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Border_size_ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Border_size_", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_AnnotateMenu {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_AnnotateMenu", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_PasteImageText {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_PasteImageText", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_CropImage {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_CropImage", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Border_color___ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Border_color___", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Show_magnifier {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_magnifier", resourceCulture); }
        }
        public static string Pause {
            get { return ResourceManager.GetString("Pause", resourceCulture); }
        }
        public static string RegionCaptureForm_ShowExitConfirmation_ShareXImageEditor {
            get { return ResourceManager.GetString("RegionCaptureForm_ShowExitConfirmation_ShareXImageEditor", resourceCulture); }
        }
        public static string DropShadowColor {
            get { return ResourceManager.GetString("DropShadowColor", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_SwitchToSelectionToolAfterDrawing {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_SwitchToSelectionToolAfterDrawing", resourceCulture); }
        }
        public static string RectangleTransparent_RectangleTransparent_Rectangle_capture_transparent {
            get { return ResourceManager.GetString("RectangleTransparent_RectangleTransparent_Rectangle_capture_transparent", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Show_position_and_size_info {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_position_and_size_info", resourceCulture); }
        }
        public static string ScreenRecordForm_Start {
            get { return ResourceManager.GetString("ScreenRecordForm_Start", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_StepType {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_StepType", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_CopyImageToClipboard {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_CopyImageToClipboard", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Show_center_crosshair {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_center_crosshair", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Show_screen_wide_crosshair {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Show_screen_wide_crosshair", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_Image {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_Image", resourceCulture); }
        }
        public static string RectangleRegion_GetColorPickerText {
            get { return ResourceManager.GetString("RectangleRegion_GetColorPickerText", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Magnifier_pixel_count_ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Magnifier_pixel_count_", resourceCulture); }
        }
        public static string ThisWindowWillCloseBeforeOpeningKeybindsPageWantContinue {
            get { return ResourceManager.GetString("ThisWindowWillCloseBeforeOpeningKeybindsPageWantContinue", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_InsertImageFile {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_InsertImageFile", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_ZoomToFitOnOpen {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_ZoomToFitOnOpen", resourceCulture); }
        }
        public static string RegionCaptureForm_TipYouCanPanImageByHoldingMouseMiddleButtonAndDragging {
            get { return ResourceManager.GetString("RegionCaptureForm_TipYouCanPanImageByHoldingMouseMiddleButtonAndDragging", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_RunAfterCaptureTasks {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_RunAfterCaptureTasks", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_RememberMenuState {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_RememberMenuState", resourceCulture); }
        }
        public static string CutOutEffectType {
            get { return ResourceManager.GetString("CutOutEffectType", resourceCulture); }
        }
        public static string ShapeManager_CreateContextMenu_Magnifier_pixel_size_ {
            get { return ResourceManager.GetString("ShapeManager_CreateContextMenu_Magnifier_pixel_size_", resourceCulture); }
        }
        public static string ShapeManager_CreateToolbar_ToolOptions {
            get { return ResourceManager.GetString("ShapeManager_CreateToolbar_ToolOptions", resourceCulture); }
        }
        public static string ScreenRecordForm_Stop {
            get { return ResourceManager.GetString("ScreenRecordForm_Stop", resourceCulture); }
        }
        public static string ScreenRecordForm_StartRecording_Click_tray_icon_to_start_recording_ {
            get { return ResourceManager.GetString("ScreenRecordForm_StartRecording_Click_tray_icon_to_start_recording_", resourceCulture); }
        }
        public static string ImageURL {
            get { return ResourceManager.GetString("ImageURL", resourceCulture); }
        }
        public static string RegionCaptureForm_SaveChangesBeforeClosingEditor {
            get { return ResourceManager.GetString("RegionCaptureForm_SaveChangesBeforeClosingEditor", resourceCulture); }
        }
        public static string CutOutBackgroundColor {
            get { return ResourceManager.GetString("CutOutBackgroundColor", resourceCulture); }
        }
        public static string RulerAngle {
            get { return ResourceManager.GetString("RulerAngle", resourceCulture); }
        }
        public static string RulerPerimeter {
            get { return ResourceManager.GetString("RulerPerimeter", resourceCulture); }
        }
        public static string RulerArea {
            get { return ResourceManager.GetString("RulerArea", resourceCulture); }
        }
        public static string RulerWidth {
            get { return ResourceManager.GetString("RulerWidth", resourceCulture); }
        }
        public static string RulerHeight {
            get { return ResourceManager.GetString("RulerHeight", resourceCulture); }
        }
        public static string RulerDistance {
            get { return ResourceManager.GetString("RulerDistance", resourceCulture); }
        }
        public static string RulerRight {
            get { return ResourceManager.GetString("RulerRight", resourceCulture); }
        }
        public static string RulerBottom {
            get { return ResourceManager.GetString("RulerBottom", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_ultra_fast {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_ultra_fast", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_super_fast {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_super_fast", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_very_fast {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_very_fast", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_faster {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_faster", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_fast {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_fast", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_medium {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_medium", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_slow {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_slow", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_slower {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_slower", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_very_slow {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_very_slow", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Preset_placebo {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Preset_placebo", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_fastest_lowest_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_fastest_lowest_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_faster_lower_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_faster_lower_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_fast_low_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_fast_low_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_medium_medium_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_medium_medium_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_slow_good_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_slow_good_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_slower_better_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_slower_better_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_slowest_best_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_slowest_best_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_high_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_high_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_low_latency {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_low_latency", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_ultra_low_latency {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_ultra_low_latency", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_NVENC_lossless {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_NVENC_lossless", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_generic_transcoding {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_generic_transcoding", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_ultra_low_latency_transcoding {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_ultra_low_latency_transcoding", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_low_latency_transcoding {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_low_latency_transcoding", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_webcam {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_webcam", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_high_quality_transcoding {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_high_quality_transcoding", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_low_latency_high_quality_transcoding {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_low_latency_high_quality_transcoding", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_prefer_speed {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_prefer_speed", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_balanced {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_balanced", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_AMF_prefer_quality {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_AMF_prefer_quality", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_software {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_software", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_software_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_software_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H265_software {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H265_software", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H265_software_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H265_software_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_VP8_software {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_VP8_software", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_VP8_software_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_VP8_software_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_VP9_software {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_VP9_software", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_VP9_software_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_VP9_software_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_MPEG4_Xvid {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_MPEG4_Xvid", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_MPEG4_Xvid_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_MPEG4_Xvid_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_NVIDIA {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_NVIDIA", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_NVIDIA_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_NVIDIA_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_HEVC_NVIDIA {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_HEVC_NVIDIA", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_HEVC_NVIDIA_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_HEVC_NVIDIA_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_AMD {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_AMD", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_AMD_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_AMD_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_HEVC_AMD {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_HEVC_AMD", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_HEVC_AMD_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_HEVC_AMD_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_Intel_Quick_Sync {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_Intel_Quick_Sync", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_H264_Intel_Quick_Sync_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_H264_Intel_Quick_Sync_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_HEVC_Intel_Quick_Sync {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_HEVC_Intel_Quick_Sync", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_HEVC_Intel_Quick_Sync_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_HEVC_Intel_Quick_Sync_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_animated_GIF {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_animated_GIF", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_animated_GIF_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_animated_GIF_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_animated_WebP {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_animated_WebP", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_animated_WebP_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_animated_WebP_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_animated_PNG {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_animated_PNG", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_animated_PNG_hint {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_animated_PNG_hint", resourceCulture); }
        }
        public static string FFmpegOptionsWindow_Codec_video_encoding {
            get { return ResourceManager.GetString("FFmpegOptionsWindow_Codec_video_encoding", resourceCulture); }
        }
        public static string ShapeManager_Spotlight_dim {
            get { return ResourceManager.GetString("ShapeManager_Spotlight_dim", resourceCulture); }
        }
        public static string ShapeManager_Spotlight_blur {
            get { return ResourceManager.GetString("ShapeManager_Spotlight_blur", resourceCulture); }
        }
        public static string ShapeManager_Spotlight_ellipse_shape {
            get { return ResourceManager.GetString("ShapeManager_Spotlight_ellipse_shape", resourceCulture); }
        }
    }
}
