<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShareX.Avalonia\ShareX.Avalonia.csproj" />
    <ProjectReference Include="..\ShareX.HelpersLib\ShareX.HelpersLib.csproj" />
    <ProjectReference Include="..\ShareX.ImageEffectsLib\ShareX.ImageEffectsLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ImageListView">
      <HintPath>..\Libs\ImageListView.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
