<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct2D1" />
    <PackageReference Include="Vortice.Direct3D11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShareX.Avalonia\ShareX.Avalonia.csproj" />
    <ProjectReference Include="..\ShareX.HelpersLib\ShareX.HelpersLib.csproj" />
    <ProjectReference Include="..\ShareX.ImageEffectsLib\ShareX.ImageEffectsLib.csproj" />
  </ItemGroup>
</Project>
