//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.Presentation.MainWindow.Localization
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class for the Avalonia main window.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal MainWindowResources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new(
                        "ShareX.Presentation.MainWindow.Localization.MainWindowResources",
                        typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string CombineImages => ResourceManager.GetString("CombineImages", resourceCulture);

        public static string FilesDroppedUploadDescription => ResourceManager.GetString("FilesDroppedUploadDescription", resourceCulture);

        public static string Horizontal => ResourceManager.GetString("Horizontal", resourceCulture);

        public static string HotkeyHint => ResourceManager.GetString("HotkeyHint", resourceCulture);

        public static string ReleaseToUploadFiles => ResourceManager.GetString("ReleaseToUploadFiles", resourceCulture);

        public static string ReleaseToUploadText => ResourceManager.GetString("ReleaseToUploadText", resourceCulture);

        public static string ShareXHotkeys => ResourceManager.GetString("ShareXHotkeys", resourceCulture);

        public static string TextDroppedUploadDescription => ResourceManager.GetString("TextDroppedUploadDescription", resourceCulture);

        public static string Vertical => ResourceManager.GetString("Vertical", resourceCulture);

        public static string About => ResourceManager.GetString("About", resourceCulture);

        public static string ActionsToolbar => ResourceManager.GetString("ActionsToolbar", resourceCulture);

        public static string AddImageEffects => ResourceManager.GetString("AddImageEffects", resourceCulture);

        public static string AddWorkflowsFromHotkeySettings => ResourceManager.GetString("AddWorkflowsFromHotkeySettings", resourceCulture);

        public static string AfterCaptureTasks => ResourceManager.GetString("AfterCaptureTasks", resourceCulture);

        public static string AfterUploadTasks => ResourceManager.GetString("AfterUploadTasks", resourceCulture);

        public static string AnalyzeImage => ResourceManager.GetString("AnalyzeImage", resourceCulture);

        public static string ApplicationSettings => ResourceManager.GetString("ApplicationSettings", resourceCulture);

        public static string AutoCapture => ResourceManager.GetString("AutoCapture", resourceCulture);

        public static string BackgroundRemover => ResourceManager.GetString("BackgroundRemover", resourceCulture);

        public static string BeautifyImage => ResourceManager.GetString("BeautifyImage", resourceCulture);

        public static string BorderlessWindow => ResourceManager.GetString("BorderlessWindow", resourceCulture);

        public static string Capture => ResourceManager.GetString("Capture", resourceCulture);

        public static string ClearThumbnailView => ResourceManager.GetString("ClearThumbnailView", resourceCulture);

        public static string ClipboardViewer => ResourceManager.GetString("ClipboardViewer", resourceCulture);

        public static string ColorPicker => ResourceManager.GetString("ColorPicker", resourceCulture);

        public static string CombineImagesDialog => ResourceManager.GetString("CombineImagesDialog", resourceCulture);

        public static string Copy => ResourceManager.GetString("Copy", resourceCulture);

        public static string CustomUploaderSettings => ResourceManager.GetString("CustomUploaderSettings", resourceCulture);

        public static string Debug => ResourceManager.GetString("Debug", resourceCulture);

        public static string DeleteSelectedFile => ResourceManager.GetString("DeleteSelectedFile", resourceCulture);

        public static string DeleteSelectedItem => ResourceManager.GetString("DeleteSelectedItem", resourceCulture);

        public static string DeletionUrl => ResourceManager.GetString("DeletionUrl", resourceCulture);

        public static string DestinationSettings => ResourceManager.GetString("DestinationSettings", resourceCulture);

        public static string Destinations => ResourceManager.GetString("Destinations", resourceCulture);

        public static string DisableHotkeys => ResourceManager.GetString("DisableHotkeys", resourceCulture);

        public static string Discord => ResourceManager.GetString("Discord", resourceCulture);

        public static string Donate => ResourceManager.GetString("Donate", resourceCulture);

        public static string DownloadSelectedUrl => ResourceManager.GetString("DownloadSelectedUrl", resourceCulture);

        public static string DragAndDropUpload => ResourceManager.GetString("DragAndDropUpload", resourceCulture);

        public static string EditImage => ResourceManager.GetString("EditImage", resourceCulture);

        public static string EnableAddImageEffects => ResourceManager.GetString("EnableAddImageEffects", resourceCulture);

        public static string EnableHotkeys => ResourceManager.GetString("EnableHotkeys", resourceCulture);

        public static string Exit => ResourceManager.GetString("Exit", resourceCulture);

        public static string File => ResourceManager.GetString("File", resourceCulture);

        public static string FileName => ResourceManager.GetString("FileName", resourceCulture);

        public static string FileNameWithExtension => ResourceManager.GetString("FileNameWithExtension", resourceCulture);

        public static string FilePath => ResourceManager.GetString("FilePath", resourceCulture);

        public static string Folder => ResourceManager.GetString("Folder", resourceCulture);

        public static string FollowShareX => ResourceManager.GetString("FollowShareX", resourceCulture);

        public static string ForumImage => ResourceManager.GetString("ForumImage", resourceCulture);

        public static string ForumLink => ResourceManager.GetString("ForumLink", resourceCulture);

        public static string ForumLinkedImage => ResourceManager.GetString("ForumLinkedImage", resourceCulture);

        public static string Fullscreen => ResourceManager.GetString("Fullscreen", resourceCulture);

        public static string HashChecker => ResourceManager.GetString("HashChecker", resourceCulture);

        public static string History => ResourceManager.GetString("History", resourceCulture);

        public static string Horizontally => ResourceManager.GetString("Horizontally", resourceCulture);

        public static string HotkeySettings => ResourceManager.GetString("HotkeySettings", resourceCulture);

        public static string HtmlImage => ResourceManager.GetString("HtmlImage", resourceCulture);

        public static string HtmlLink => ResourceManager.GetString("HtmlLink", resourceCulture);

        public static string HtmlLinkedImage => ResourceManager.GetString("HtmlLinkedImage", resourceCulture);

        public static string IconConverter => ResourceManager.GetString("IconConverter", resourceCulture);

        public static string Image => ResourceManager.GetString("Image", resourceCulture);

        public static string ImageBeautifier => ResourceManager.GetString("ImageBeautifier", resourceCulture);

        public static string ImageCombiner => ResourceManager.GetString("ImageCombiner", resourceCulture);

        public static string ImageComparer => ResourceManager.GetString("ImageComparer", resourceCulture);

        public static string ImageDimensions => ResourceManager.GetString("ImageDimensions", resourceCulture);

        public static string ImageEditor => ResourceManager.GetString("ImageEditor", resourceCulture);

        public static string ImageEffects => ResourceManager.GetString("ImageEffects", resourceCulture);

        public static string ImageHistory => ResourceManager.GetString("ImageHistory", resourceCulture);

        public static string ImageSplitter => ResourceManager.GetString("ImageSplitter", resourceCulture);

        public static string ImageThumbnailer => ResourceManager.GetString("ImageThumbnailer", resourceCulture);

        public static string ImageViewer => ResourceManager.GetString("ImageViewer", resourceCulture);

        public static string IndexFolder => ResourceManager.GetString("IndexFolder", resourceCulture);

        public static string InspectWindow => ResourceManager.GetString("InspectWindow", resourceCulture);

        public static string LastRegion => ResourceManager.GetString("LastRegion", resourceCulture);

        public static string MarkdownImage => ResourceManager.GetString("MarkdownImage", resourceCulture);

        public static string MarkdownLink => ResourceManager.GetString("MarkdownLink", resourceCulture);

        public static string MarkdownLinkedImage => ResourceManager.GetString("MarkdownLinkedImage", resourceCulture);

        public static string Metadata => ResourceManager.GetString("Metadata", resourceCulture);

        public static string Monitor => ResourceManager.GetString("Monitor", resourceCulture);

        public static string MonitorTest => ResourceManager.GetString("MonitorTest", resourceCulture);

        public static string NoImageEffectPresets => ResourceManager.GetString("NoImageEffectPresets", resourceCulture);

        public static string NoWindowsFound => ResourceManager.GetString("NoWindowsFound", resourceCulture);

        public static string OCR => ResourceManager.GetString("OCR", resourceCulture);

        public static string OCRImage => ResourceManager.GetString("OCRImage", resourceCulture);

        public static string Open => ResourceManager.GetString("Open", resourceCulture);

        public static string PinToScreen => ResourceManager.GetString("PinToScreen", resourceCulture);

        public static string PinToScreenDialog => ResourceManager.GetString("PinToScreenDialog", resourceCulture);

        public static string QRCode => ResourceManager.GetString("QRCode", resourceCulture);

        public static string RecentItems => ResourceManager.GetString("RecentItems", resourceCulture);

        public static string Region => ResourceManager.GetString("Region", resourceCulture);

        public static string RegionLight => ResourceManager.GetString("RegionLight", resourceCulture);

        public static string RegionTransparent => ResourceManager.GetString("RegionTransparent", resourceCulture);

        public static string RestartAsAdministrator => ResourceManager.GetString("RestartAsAdministrator", resourceCulture);

        public static string Ruler => ResourceManager.GetString("Ruler", resourceCulture);

        public static string RunAction => ResourceManager.GetString("RunAction", resourceCulture);

        public static string ScreenColorPicker => ResourceManager.GetString("ScreenColorPicker", resourceCulture);

        public static string ScreenRecording => ResourceManager.GetString("ScreenRecording", resourceCulture);

        public static string ScreenRecordingGif => ResourceManager.GetString("ScreenRecordingGif", resourceCulture);

        public static string ScreenshotsFolder => ResourceManager.GetString("ScreenshotsFolder", resourceCulture);

        public static string ScrollingCapture => ResourceManager.GetString("ScrollingCapture", resourceCulture);

        public static string SearchWithBingVisualSearch => ResourceManager.GetString("SearchWithBingVisualSearch", resourceCulture);

        public static string SearchWithGoogleLens => ResourceManager.GetString("SearchWithGoogleLens", resourceCulture);

        public static string ShareSelectedUrl => ResourceManager.GetString("ShareSelectedUrl", resourceCulture);

        public static string ShortenSelectedUrl => ResourceManager.GetString("ShortenSelectedUrl", resourceCulture);

        public static string ShortenUrl => ResourceManager.GetString("ShortenUrl", resourceCulture);

        public static string ShortenedUrl => ResourceManager.GetString("ShortenedUrl", resourceCulture);

        public static string ShowCursor => ResourceManager.GetString("ShowCursor", resourceCulture);

        public static string ShowDebugLog => ResourceManager.GetString("ShowDebugLog", resourceCulture);

        public static string ShowErrors => ResourceManager.GetString("ShowErrors", resourceCulture);

        public static string ShowQRCode => ResourceManager.GetString("ShowQRCode", resourceCulture);

        public static string ShowResponse => ResourceManager.GetString("ShowResponse", resourceCulture);

        public static string ShowShareX => ResourceManager.GetString("ShowShareX", resourceCulture);

        public static string StopUpload => ResourceManager.GetString("StopUpload", resourceCulture);

        public static string TaskSettings => ResourceManager.GetString("TaskSettings", resourceCulture);

        public static string TestFileUpload => ResourceManager.GetString("TestFileUpload", resourceCulture);

        public static string TestImageUpload => ResourceManager.GetString("TestImageUpload", resourceCulture);

        public static string TestTextUpload => ResourceManager.GetString("TestTextUpload", resourceCulture);

        public static string TestUrlSharing => ResourceManager.GetString("TestUrlSharing", resourceCulture);

        public static string TestUrlShortener => ResourceManager.GetString("TestUrlShortener", resourceCulture);

        public static string Text => ResourceManager.GetString("Text", resourceCulture);

        public static string ThumbnailFile => ResourceManager.GetString("ThumbnailFile", resourceCulture);

        public static string ThumbnailImage => ResourceManager.GetString("ThumbnailImage", resourceCulture);

        public static string ThumbnailUrl => ResourceManager.GetString("ThumbnailUrl", resourceCulture);

        public static string Tools => ResourceManager.GetString("Tools", resourceCulture);

        public static string UntitledTask => ResourceManager.GetString("UntitledTask", resourceCulture);

        public static string Upload => ResourceManager.GetString("Upload", resourceCulture);

        public static string UploadClipboard => ResourceManager.GetString("UploadClipboard", resourceCulture);

        public static string UploadFile => ResourceManager.GetString("UploadFile", resourceCulture);

        public static string UploadFolder => ResourceManager.GetString("UploadFolder", resourceCulture);

        public static string UploadSelectedFile => ResourceManager.GetString("UploadSelectedFile", resourceCulture);

        public static string UploadText => ResourceManager.GetString("UploadText", resourceCulture);

        public static string UploadUrl => ResourceManager.GetString("UploadUrl", resourceCulture);

        public static string Url => ResourceManager.GetString("Url", resourceCulture);

        public static string Vertically => ResourceManager.GetString("Vertically", resourceCulture);

        public static string VideoConverter => ResourceManager.GetString("VideoConverter", resourceCulture);

        public static string VideoThumbnailer => ResourceManager.GetString("VideoThumbnailer", resourceCulture);

        public static string Window => ResourceManager.GetString("Window", resourceCulture);

        public static string Workflows => ResourceManager.GetString("Workflows", resourceCulture);
    }
}
