using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;

namespace ShareX.Platform.Linux;

/// <summary>
/// File manager context menu entries for Nautilus (GNOME), Dolphin (KDE Plasma), Nemo (Cinnamon), Caja (MATE) and Thunar (Xfce).
/// </summary>
/// <remarks>Entries are written for every supported file manager so switching desktops keeps them working.</remarks>
public sealed class LinuxShellIntegrationService : IShellIntegrationService
{
    private static readonly string[] ImageMimeTypes = ["image/png", "image/jpeg", "image/gif", "image/bmp", "image/webp", "image/tiff", "image/avif"];
    private static readonly string[] ImageExtensions = ["png", "jpg", "jpeg", "gif", "bmp", "webp", "tif", "tiff", "avif"];

    private readonly string dataHome;
    private readonly string configHome;

    public LinuxShellIntegrationService(XdgPathService paths)
        : this(paths.DataHome, paths.ConfigHome)
    {
    }

    public LinuxShellIntegrationService(string dataHome, string configHome)
    {
        this.dataHome = dataHome;
        this.configHome = configHome;
    }

    public FeatureSupport Support => FeatureSupport.Supported;

    internal string NautilusScriptPath(ShellMenuEntry entry) => Path.Combine(dataHome, "nautilus", "scripts", SafeFileName(entry.Label));

    internal string CajaScriptPath(ShellMenuEntry entry) => Path.Combine(configHome, "caja", "scripts", SafeFileName(entry.Label));

    internal string DolphinServiceMenuPath(ShellMenuEntry entry) => Path.Combine(dataHome, "kio", "servicemenus", entry.Id + ".desktop");

    internal string NemoActionPath(ShellMenuEntry entry) => Path.Combine(dataHome, "nemo", "actions", entry.Id + ".nemo_action");

    internal string ThunarActionsPath => Path.Combine(configHome, "Thunar", "uca.xml");

    public bool IsRegistered(ShellMenuEntry entry)
    {
        string expectedExec = DesktopEntry.BuildExec(entry.ExecutablePath, entry.Arguments, appendFileCode: true);
        string path = DolphinServiceMenuPath(entry);

        if (File.Exists(path) && File.ReadAllText(path).Contains("Exec=" + expectedExec, StringComparison.Ordinal))
        {
            return true;
        }

        path = NautilusScriptPath(entry);
        return File.Exists(path) && File.ReadAllText(path).Contains(ShellQuote(entry.ExecutablePath), StringComparison.Ordinal);
    }

    public void Register(ShellMenuEntry entry)
    {
        Unregister(entry);

        string script = CreateScript(entry);
        WriteExecutable(NautilusScriptPath(entry), script);
        WriteExecutable(CajaScriptPath(entry), script);
        // Plasma 5.24+ ignores service menus that are not executable.
        WriteExecutable(DolphinServiceMenuPath(entry), CreateDolphinServiceMenu(entry));
        WriteFile(NemoActionPath(entry), CreateNemoAction(entry));
        UpdateThunarActions(entry, register: true);
    }

    public void Unregister(ShellMenuEntry entry)
    {
        foreach (string path in new[] { NautilusScriptPath(entry), CajaScriptPath(entry), DolphinServiceMenuPath(entry), NemoActionPath(entry) })
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }

        UpdateThunarActions(entry, register: false);
    }

    internal static string CreateScript(ShellMenuEntry entry)
    {
        // Nautilus and Caja pass the selected files as arguments. Images only entries still show for every file, so filter here.
        StringBuilder builder = new StringBuilder();
        builder.Append("#!/bin/sh\n");
        builder.Append("# Generated by ShareX. ").Append(entry.Id).Append('\n');

        if (entry.Target == ShellMenuTarget.Images)
        {
            builder.Append("for file in \"$@\"; do\n");
            builder.Append("  case \"$(printf '%s' \"$file\" | tr '[:upper:]' '[:lower:]')\" in\n");
            builder.Append("    ").Append(string.Join("|", ImageExtensions.Select(e => "*." + e))).Append(") ;;\n");
            builder.Append("    *) exit 0 ;;\n");
            builder.Append("  esac\n");
            builder.Append("done\n");
        }

        builder.Append("exec ").Append(ShellQuote(entry.ExecutablePath));

        foreach (string argument in entry.Arguments)
        {
            builder.Append(' ').Append(ShellQuote(argument));
        }

        builder.Append(" \"$@\"\n");
        return builder.ToString();
    }

    internal static string CreateDolphinServiceMenu(ShellMenuEntry entry)
    {
        string mimeTypes = entry.Target == ShellMenuTarget.Images ? string.Join(";", ImageMimeTypes) + ";" : "all/allfiles;inode/directory;";
        string action = "sharex_" + SafeIdentifier(entry.Id);

        StringBuilder builder = new StringBuilder();
        builder.Append("[Desktop Entry]\n");
        builder.Append("Type=Service\n");
        builder.Append("X-KDE-ServiceTypes=KonqPopupMenu/Plugin\n");
        builder.Append("MimeType=").Append(mimeTypes).Append('\n');
        builder.Append("Actions=").Append(action).Append('\n');
        builder.Append("X-KDE-Priority=TopLevel\n\n");
        builder.Append("[Desktop Action ").Append(action).Append("]\n");
        builder.Append("Name=").Append(DesktopEntry.EscapeValue(entry.Label)).Append('\n');

        if (!string.IsNullOrEmpty(entry.Icon))
        {
            builder.Append("Icon=").Append(DesktopEntry.EscapeValue(entry.Icon)).Append('\n');
        }

        builder.Append("Exec=").Append(DesktopEntry.BuildExec(entry.ExecutablePath, entry.Arguments, appendFileCode: true)).Append('\n');
        return builder.ToString();
    }

    internal static string CreateNemoAction(ShellMenuEntry entry)
    {
        StringBuilder builder = new StringBuilder();
        builder.Append("[Nemo Action]\n");
        builder.Append("Active=true\n");
        builder.Append("Name=").Append(entry.Label.Replace("_", "__")).Append('\n');
        builder.Append("Comment=").Append(entry.Label).Append('\n');
        builder.Append("Exec=").Append(DesktopEntry.BuildExec(entry.ExecutablePath, entry.Arguments, appendFileCode: true)).Append('\n');

        if (!string.IsNullOrEmpty(entry.Icon))
        {
            builder.Append("Icon-Name=").Append(entry.Icon).Append('\n');
        }

        builder.Append("Selection=NotNone\n");
        builder.Append(entry.Target == ShellMenuTarget.Images
            ? "Extensions=" + string.Join(";", ImageExtensions) + ";\n"
            : "Extensions=any;dir;\n");
        return builder.ToString();
    }

    private void UpdateThunarActions(ShellMenuEntry entry, bool register)
    {
        string path = ThunarActionsPath;

        if (!register && !File.Exists(path))
        {
            return;
        }

        XDocument document;

        try
        {
            document = File.Exists(path) ? XDocument.Load(path) : new XDocument(new XElement("actions"));
        }
        catch (System.Xml.XmlException)
        {
            // Leave a file we cannot parse alone rather than overwrite the user's actions.
            return;
        }

        XElement root = document.Root ?? new XElement("actions");
        string uniqueId = "sharex-" + entry.Id;

        foreach (XElement existing in root.Elements("action").Where(a => (string?)a.Element("unique-id") == uniqueId).ToList())
        {
            existing.Remove();
        }

        if (register)
        {
            string command = string.Join(" ", new[] { entry.ExecutablePath }.Concat(entry.Arguments).Select(ShellQuote)) + " %F";
            XElement action = new XElement("action",
                new XElement("icon", entry.Icon ?? ""),
                new XElement("name", entry.Label),
                new XElement("submenu", ""),
                new XElement("unique-id", uniqueId),
                new XElement("command", command),
                new XElement("description", entry.Label),
                new XElement("range", ""),
                new XElement("patterns", entry.Target == ShellMenuTarget.Images ? string.Join(";", ImageExtensions.Select(e => "*." + e)) : "*"));

            if (entry.Target == ShellMenuTarget.Images)
            {
                action.Add(new XElement("image-files"));
            }
            else
            {
                action.Add(new XElement("directories"), new XElement("audio-files"), new XElement("image-files"),
                    new XElement("other-files"), new XElement("text-files"), new XElement("video-files"));
            }

            root.Add(action);
        }

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        document.Save(path);
    }

    /// <summary>Quotes an argument for POSIX sh.</summary>
    internal static string ShellQuote(string value) => "'" + value.Replace("'", "'\\''") + "'";

    private static string SafeFileName(string label)
    {
        char[] invalid = ['/', '\0'];
        return new string(label.Select(c => invalid.Contains(c) ? '_' : c).ToArray());
    }

    private static string SafeIdentifier(string id) => new string(id.Select(c => char.IsLetterOrDigit(c) ? char.ToLowerInvariant(c) : '_').ToArray());

    private static void WriteFile(string path, string content)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content, new UTF8Encoding(false));
    }

    private static void WriteExecutable(string path, string content)
    {
        WriteFile(path, content);

        if (!OperatingSystem.IsWindows())
        {
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
                UnixFileMode.GroupRead | UnixFileMode.GroupExecute | UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
        }
    }
}
