<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShareX.HelpersLib\ShareX.HelpersLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\OAuthCallbackPage.html" />
  </ItemGroup>
</Project>
