<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>ShareX_Icon.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Description>Screen capture, file sharing and productivity tool</Description>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
    <ApplicationUseCompatibleTextRendering>false</ApplicationUseCompatibleTextRendering>
    <ApplicationDefaultFont>Microsoft Sans Serif, 8.25pt</ApplicationDefaultFont>
    <CETCompat>false</CETCompat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Win32.Interoperability" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" />
    <PackageReference Include="ZXing.Net" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShareX.Avalonia\ShareX.Avalonia.csproj" />
    <ProjectReference Include="..\ShareX.Tools\ShareX.Tools.csproj" />
    <ProjectReference Include="..\ShareX.HistoryLib\ShareX.HistoryLib.csproj" />
    <ProjectReference Include="..\ShareX.ImageEditor.App\ShareX.ImageEditor.App.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
    <ProjectReference Include="..\ShareX.ImageEditor\ShareX.ImageEditor.csproj" />
    <ProjectReference Include="..\ShareX.ImageEffectsLib\ShareX.ImageEffectsLib.csproj" />
    <ProjectReference Include="..\ShareX.MediaLib\ShareX.MediaLib.csproj" />
    <ProjectReference Include="..\ShareX.NativeMessagingHost\ShareX.NativeMessagingHost.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
    <ProjectReference Include="..\ShareX.ScreenCaptureLib\ShareX.ScreenCaptureLib.csproj" />
    <ProjectReference Include="..\ShareX.HelpersLib\ShareX.HelpersLib.csproj" />
    <ProjectReference Include="..\ShareX.UploadersLib\ShareX.UploadersLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host-manifest-chrome.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="host-manifest-firefox.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ShareX_File_Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
  </ItemGroup>
</Project>
