//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareX.HistoryLib.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareX.HistoryLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap application_block {
            get {
                object obj = ResourceManager.GetObject("application_block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap globe {
            get {
                object obj = ResourceManager.GetObject("globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Filtered: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryForm_UpdateItemCount___Filtered___0_ {
            get {
                return ResourceManager.GetString("HistoryForm_UpdateItemCount___Filtered___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryForm_UpdateItemCount_Total___0_ {
            get {
                return ResourceManager.GetString("HistoryForm_UpdateItemCount_Total___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Copy {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletion URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Deletion_URL {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Deletion_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_File {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_File_name {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_File_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name with extension과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_File_name_with_extension {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_File_name_with_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_File_path {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_File_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Folder {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forum (BBCode) image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Forum__BBCode__image {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Forum__BBCode__image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forum (BBCode) link과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Forum__BBCode__link {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Forum__BBCode__link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forum (BBCode) linked image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Forum__BBCode__linked_image {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Forum__BBCode__linked_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_HTML_image {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_HTML_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML link과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_HTML_link {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_HTML_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML linked image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_HTML_linked_image {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_HTML_linked_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Image {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Image_preview {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Image_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Markdown image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Markdown__image {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Markdown__image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Markdown link과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Markdown__link {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Markdown__link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Markdown linked image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Markdown__linked_image {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Markdown__linked_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_More_info {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_More_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Open {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortened URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Shortened_URL {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Shortened_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Show {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Text {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thumbnail URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_Thumbnail_URL {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_Thumbnail_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_InitializeComponent_URL {
            get {
                return ResourceManager.GetString("HistoryItemManager_InitializeComponent_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML link ({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_UpdateTexts_HTML_link___0__ {
            get {
                return ResourceManager.GetString("HistoryItemManager_UpdateTexts_HTML_link___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLs ({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryItemManager_UpdateTexts_URLs___0__ {
            get {
                return ResourceManager.GetString("HistoryItemManager_UpdateTexts_URLs___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryManager_GetHistoryItems_Error {
            get {
                return ResourceManager.GetString("HistoryManager_GetHistoryItems_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured while reading XML file: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HistoryManager_GetHistoryItems_Error_occured_while_reading_XML_file___0_ {
            get {
                return ResourceManager.GetString("HistoryManager_GetHistoryItems_Error_occured_while_reading_XML_file___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap notebook {
            get {
                object obj = ResourceManager.GetObject("notebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Copy name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ObjectListView_ObjectListView_Copy_name {
            get {
                return ResourceManager.GetString("ObjectListView_ObjectListView_Copy_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ObjectListView_ObjectListView_Copy_value {
            get {
                return ResourceManager.GetString("ObjectListView_ObjectListView_Copy_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ObjectListView_ObjectListView_Name {
            get {
                return ResourceManager.GetString("ObjectListView_ObjectListView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ObjectListView_ObjectListView_Value {
            get {
                return ResourceManager.GetString("ObjectListView_ObjectListView_Value", resourceCulture);
            }
        }
    }
}
