<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64;ARM64</Platforms>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\closedhand.cur" />
    <AvaloniaResource Include="Assets\Crosshair.cur" />
    <AvaloniaResource Include="Assets\openhand.cur" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShareX.Avalonia\ShareX.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ShareX.ImageEditor.Presentation.Theming" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\emoji-catalog.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Vortice.Direct2D1" VersionOverride="3.8.3" />
    <PackageReference Include="Vortice.DXGI" VersionOverride="3.8.3" />
  </ItemGroup>
</Project>
